In [1]:
from vistiq.io import ImageWriterConfig, ImageWriter, ImageLoader, ImageLoaderConfig, unstack_image
from vistiq.utils import ArrayIteratorConfig, check_device, resolve_futures 
from vistiq.core import Tiler, TilerConfig, Untiler, UntilerConfig
from vistiq.preprocess import FuncProcessor, FuncProcessorConfig, PreprocessFlow, PreprocessFlowConfig, ResizeConfig, Resize, RescaleConfig, Rescale, DoG, DoGConfig, PreprocessorConfig, Preprocessor
from vistiq.segment import RegionFilterConfig, RegionFilter, RangeFilterConfig, RangeFilter, RegionAnalyzerConfig, RegionAnalyzer 
from vistiq.segment import MicroSAMSegmenter, MicroSAMSegmenterConfig, MicroSAMMerger, MicroSAMMergerConfig
from vistiq.segment import TiledSegmentationFlow, TiledSegmentationFlowConfig, SegmentationFlow, SegmentationFlowConfig
from vistiq.analysis import CoincidenceDetectorConfig, CoincidenceDetector, AnalysisFlowConfig, AnalysisFlow, IoSMetricsCalculatorConfig
from vistiq.core import labels_to_masks
from vistiq.analysis.overlap import (
    OverlapCalculator,
    LabelOverlapCalculatorConfig,   # or BoxOverlapCalculatorConfig / MaskOverlapCalculatorConfig
    IoSMetricsCalculatorConfig,
    metrics_calculator_configs,
    region_map_from_dataframe,      # if using region maps from DataFrames
)
from vistiq.analysis import MatrixAggregator, MatrixAggregatorConfig, MatrixCombiner, MatrixCombinerConfig
from vistiq.constant.matrix import UPPER
from vistiq.constant import LOWER_ND
from vistiq.segment.select import ValueFilter, ValueFilterConfig, TopKFilter, TopKFilterConfig
from vistiq.graph import NXGraphBuilder, NXGraphBuilderConfig, NXGraphQuery, NXGraphQueryConfig

from prefect import flow, task
from prefect.task_runners import ProcessPoolTaskRunner
from prefect.futures import wait
from prefect.futures import resolve_futures_to_results

import stackview
import os
import copy
import numpy as np
import math
import logging
import pandas as pd
import itertools

from typing import Any, List, Tuple
from pathlib import Path

FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
2026-06-17 22:30:33,913 - INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'

# Configure logger and check availability of accelerators

In [2]:
import vistiq
logger = logging.getLogger(vistiq.__name__)

logger.info(f"Available Torch accelerators: {check_device()}")

2026-06-17 22:30:40,009 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:30:40,010 - INFO - Available Torch accelerators: mps

# Load image

In [3]:
#path="/standard/vol191/siegristlab/Microsam_Segmentation/Conditional Split/control_24+48/DCP1/1_Dpn.tif"
#path="/standard/vol191/siegristlab/Microsam_Segmentation/24h/AkhGal4 x OR Susie/Scrib488 Dpn555 EdU 647/Raw files/Animal 1.lif"
path="Animal 1.lif"
#path="/Users/khs3z/Documents/SDS_/projects/Siegrist/Microsam_Segmentation/24h/AkhGal4 x OR Susie/Scrib488 Dpn555 EdU 647/Animal 1.lif"

scene_index = 0

embedding_path = "./embeddings"
#embedding_path = "/standard/vol191/siegristlab/Sagar/microsam/embeddings/"

In [4]:
ilc = ImageLoaderConfig(
    squeeze=True, 
    rename_channel={"Red": "Dpn", "Green": "Scrib", "Blue": "EdU"}, 
    scene_index=scene_index, 
    split_channels=False,
    substack="Z:20-50"
)
img, metadata = ImageLoader(ilc).run(path)

2026-06-17 22:30:40,700 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 22:30:40,766 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 22:30:40,770 - INFO - Loading image from: Animal 1.lif
2026-06-17 22:30:41,912 - INFO - Scenes found: ('Series001', 'Series002', 'Series003')
2026-06-17 22:30:41,913 - INFO - Applying substack={'Z': slice(19, 50, None)}
2026-06-17 22:30:42,019 - INFO - Loaded image: Animal 1.lif scene=0 -> shape=(3, 31, 512, 512) dtype=uint8, channel_names=['Scrib', 'EdU', 'Dpn']
2026-06-17 22:30:42,020 - INFO - Loaded image with shape: (3, 31, 512, 512), dtype: uint8
2026-06-17 22:30:42,021 - INFO - Finished in state Completed()

In [5]:
if "C" in metadata["axes"]:
    vimg = np.concatenate(np.unstack(img, axis=0), axis=-1)
else:
    vimg = img
stackview.slice(vimg)
#stackview.switch(img, colormap=["pure_green", "pure_blue", "pure_red"], toggleable=True)

HBox(children=(VBox(children=(VBox(children=(HBox(children=(VBox(children=(ImageWidget(height=512, width=1536)…

# Preprocess

In [6]:
tissue_ppcfg = PreprocessFlowConfig(
    processors = [
        RescaleConfig(
            low=2, 
            high=98, 
            dtype=np.uint8, 
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="skimage.filters.gaussian",
            kwargs={"sigma": 1.0},
            iterator_config=ArrayIteratorConfig(slice_def=(-2,-1)) # YX over each Z-plane and channel
        ),
        FuncProcessorConfig(
            func="skimage.exposure.adjust_gamma",
            kwargs={"gamma": 0.2},
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="skimage.exposure.adjust_sigmoid",
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        RescaleConfig(
            dtype=np.uint8, 
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="numpy.max", 
            kwargs={"axis":("C")}, # Project all channels into one
            strict_axis=False,     # don't throw exception if the input is a single channel image already
            dtype=np.uint16,
        ),
    ]
)
#c_img, c_metadata = PreprocessFlow(tissue_ppcfg).run(img, metadata=metadata, workers=-1)
#metadata, c_metadata

In [7]:
# stackview.slice(c_img)

# Configuration for 3D Tissue Segmentation

In [8]:
mscfg = MicroSAMSegmenterConfig(
    iterator_config=ArrayIteratorConfig(slice_def=()),
    embedding_path=embedding_path,
)

rfcfg = RegionFilterConfig(
    filters=[
        RangeFilterConfig(
            attribute="cross_sectional_area-xy", 
            range=(2000, np.inf)
        ),
        RangeFilterConfig(
            attribute="cross_sectional_area-xz", 
            range=(2000, np.inf)
        ),
        RangeFilterConfig(
            attribute="cross_sectional_area-yz", 
            range=(2000, np.inf)
        ),
        RangeFilterConfig(
            attribute="aspect_ratio", 
            range=(0.5, 1.0)
        ),
    ]
)

tsfcfg = TiledSegmentationFlowConfig(
    segmenter = mscfg,
    region_filter = rfcfg,
    tile_factor=(3,3),
    resize_factor=(0.25, 0.25),
    iou_threshold=0.5,
    consensus_threshold=0.75,
)

# Configuration for Region Analysis

In [9]:
racfg = RegionAnalyzerConfig(
    properties=["slice_annotations","volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
    iterator_config = ArrayIteratorConfig(slice_def=()),
    output_type="dataframe",
    map_axes=True,
)
ra = RegionAnalyzer(racfg)

# Configuration for Cell Segmentation

In [10]:
# specify preprocessing config for cells
cell_ppcfg = PreprocessFlowConfig(
    processors = [
        #DoGConfig(
        #    sigma_low=1, # 5, 
        #    sigma_high=2, #12, 
        #    normalize=True,
        #    iterator_config=ArrayIteratorConfig(slice_def=(-2,-1)) # YX over each Z focal plane and channel
        #)
    ]
)

In [11]:
# Specify segmentation config
mscfg = MicroSAMSegmenterConfig(
    iterator_config=ArrayIteratorConfig(slice_def=()),
    embedding_path=embedding_path,
    #gpu_fraction=0.3,
)

min_cell_radius = 2.0
max_cell_radius = 7.0
rfcfg = RegionFilterConfig(
    filters=[
        RangeFilterConfig(
            attribute="cross_sectional_area-xy", 
            range=(np.pi*min_cell_radius**2, np.pi*max_cell_radius**2)
        )
    ]
)

cell_sfcfg = SegmentationFlowConfig(
    segmenter = mscfg,
    region_filter = rfcfg,
)

In [12]:
@flow
def analyze_cells(labels: list[np.ndarray], metadata: list[dict[str, Any]]) -> list[pd.DataFrame]:
    print ([l.shape for l in labels])
    print ([m["channel_names"] for m in metadata])
    racfg = RegionAnalyzerConfig(
        properties=["volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
        iterator_config = ArrayIteratorConfig(slice_def=()),
        output_type="dataframe"
    )
    ra = RegionAnalyzer(racfg)

    measurements = ra.run.map(labels, metadata=metadata)

    cdcfg = CoincidenceDetectorConfig(
        method="ios",
        iterator_config=ArrayIteratorConfig(slice_def=()),
        mode="outline",
    )
    label_index_combinations = list(itertools.combinations(range(len(labels)), 2))
    l1 = [labels[c[0]] for c in label_index_combinations]
    l2 = [labels[c[1]] for c in label_index_combinations]
    sn = [(metadata[c[0]]["channel_names"][0], metadata[c[1]]["channel_names"][0]) for c in label_index_combinations]
    print (sn)
    #for la1, la2, sna in zip(l1,l2,sn): 
    cim = CoincidenceDetector(cdcfg).run.map(l1, l2, stack_names=sn)
    return measurements

In [13]:
acfg = AnalysisFlowConfig(
    region_analyzer = RegionAnalyzerConfig(
        properties=["volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
        iterator_config = ArrayIteratorConfig(slice_def=()),
        output_type="dataframe",
        index_on="object_id",
        map_axes=True,
    ),
    #coincidence_detector = CoincidenceDetectorConfig(
    #    method=IoSMetricsCalculatorConfig(),
    #    iterator_config=ArrayIteratorConfig(slice_def=()),
    #    mode="outline",
    #),
    overlap_calculator = LabelOverlapCalculatorConfig(
        metrics_calculators = [IoSMetricsCalculatorConfig()],
        output_type="dataframe",
        annotate=True,
        triangle=7,
    ),
    overlap_filter = ValueFilterConfig(
        ref_value=0.5,
        axis=0,
        operator=">",
        triangle=LOWER_ND,
        output="masked_values",
    ),
    overlap_aggregator = MatrixAggregatorConfig(
        operation="count",
        axis=1,
    ),
)

In [14]:
@flow
def full_pipeline(img_path, scene_index=0, outdir=".", embedding_path="embeddings"):
    # load image
    img, metadata = ImageLoader(ilc).run(img_path)
    
    # TISSUE - brain lobes
    # preprocess
    tissue_img, tissue_metadata = PreprocessFlow(tissue_ppcfg).run(img, metadata=metadata, workers=-1)
    tissue_metadata = copy.deepcopy(tissue_metadata)
    tissue_metadata["channel_names"] = ["Lobe"]
    # segment tissue
    tissue_labels = TiledSegmentationFlow(tsfcfg).run(tissue_img, metadata=tissue_metadata, workers=2, verbose=0)

    # BRAIN - all tissue combined
    #tissue_masks = labels_to_masks(tissue_labels)
    brain_label = (tissue_labels>0).astype("uint16")
    brain_metadata = copy.deepcopy(tissue_metadata)
    brain_metadata["channel_names"] = ["Brain"]
    
    # CELLS
    # preprocess
    preprocessed, preprocessed_metadata = PreprocessFlow(cell_ppcfg).run(img, metadata=metadata)
    # split channels
    channels, channel_metadata = unstack_image(preprocessed, preprocessed_metadata, axis=metadata["channel_axis"], strict=False)
    # segment each channel separately
    cell_labels = SegmentationFlow(cell_sfcfg).mapped_run(channels, metadata=channel_metadata)
    
    # Analyze CELLS and TISSUE
    # analyze regions in each channel separately
    combined_labels = [brain_label, tissue_labels, *cell_labels]
    combined_metadata = [brain_metadata, tissue_metadata, *channel_metadata]
    measurements = AnalysisFlow(acfg).run(combined_labels, metadata=combined_metadata)
    # measurements = analyze_cells([*cell_labels, lobe_labels, brain_label], metadata=[*channel_metadata, c_metadata, b_metadata])

    # save labels
    fname_stem = Path(img_path).stem
    imc = ImageWriterConfig(overwrite=True)
    outpaths = [os.path.join(outdir, f'{fname_stem}.scene-{meta.get("scene_index","")}.tif') for meta in combined_metadata]
    # print (outpaths)
    ImageWriter(imc).run.map(combined_labels, outpaths, metadata=combined_metadata)
    
    # make sure to resolve the futures to results
    return (
        resolve_futures(combined_labels),
        resolve_futures(combined_metadata),
        resolve_futures(measurements),
    )

In [15]:
combined_labels, combined_metadata, measurements = full_pipeline(path, scene_index=scene_index, outdir=".", embedding_path=embedding_path)

2026-06-17 22:30:42,865 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:30:43,108 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:30:43,467 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-2fc1-726a-8000-566e83ad2ff9/set_state "HTTP/1.1 201 Created"
2026-06-17 22:30:43,552 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-2fc1-726a-8000-566e83ad2ff9 "HTTP/1.1 200 OK"
2026-06-17 22:30:43,613 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 22:30:43,664 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 22:30:43,666 - INFO - Beginning flow run 'determined-lionfish' for flow 'full-pipeline'
2026-06-17 22:30:43,671 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33585-2fc1-726a-8000-566e83ad2ff9
2026-06-17 22:30:43,678 - INFO - Loading image from: Animal 1.lif
2026-06-17 22:30:43,758 - INFO - Scenes found: ('Series001', 'Series002', 'Series003')
2026-06-17 22:30:43,758 - INFO - Applying substack={'Z': slice(19, 50, None)}
2026-06-17 22:30:43,807 - INFO - Loaded image: Animal 1.lif scene=0 -> shape=(3, 31, 512, 512) dtype=uint8, channel_names=['Scrib', 'EdU', 'Dpn']
2026-06-17 22:30:43,808 - INFO - Loaded image with shape: (3, 31, 512, 512), dtype: uint8
2026-06-17 22:30:43,809 - INFO - Finished in state Completed()
2026-06-17 22:30:43,809 - INFO - Setting up PreprocessFlow with Rescale,FuncProcessor,FuncProcessor,FuncProcessor,Rescale,FuncProcessor
2026-06-17 22:30:43,811 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ece03cf4-776b-46e7-a39b-3fdfabe14f28 "HTTP/1.1 200 OK"
2026-06-17 22:30:44,286 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:30:44,430 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-06-17 22:30:44,587 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:30:45,002 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:30:45,188 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-4c7c-72b7-8000-b9ba3bf3d1a1 "HTTP/1.1 204 No Content"
2026-06-17 22:30:45,514 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-4c7c-72b7-8000-b9ba3bf3d1a1/set_state "HTTP/1.1 201 Created"
2026-06-17 22:30:45,657 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-4c7c-72b7-8000-b9ba3bf3d1a1 "HTTP/1.1 200 OK"
2026-06-17 22:30:45,662 - INFO - Beginning subflow run 'autogenerated: PreprocessFlow' for flow 'Workflow.run'
2026-06-17 22:30:45,665 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33585-4c7c-72b7-8000-b9ba3bf3d1a1
2026-06-17 22:30:45,773 - INFO - Running PreprocessFlow with 6 processors
2026-06-17 22:30:45,824 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/c32a815c-c449-48e0-a2fa-4b35e8784bee "HTTP/1.1 200 OK"
2026-06-17 22:30:45,851 - INFO - Running preprocessor Rescale, on stack of type uint8, True
2026-06-17 22:30:45,925 - INFO - Running Rescale with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint8'> low=2.0 high=98.0
2026-06-17 22:30:45,925 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:45,925 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
2026-06-17 22:30:46,000 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.1s finished
2026-06-17 22:30:46,013 - INFO - Reshaped results to shape (3, 31, 512, 512)
2026-06-17 22:30:46,014 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-06-17 22:30:46,014 - INFO - Metadata updated in Rescale: 1 key(s) changed
2026-06-17 22:30:46,014 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:46,015 - INFO - Finished in state Completed()
2026-06-17 22:30:46,091 - INFO - Finished in state Completed()
2026-06-17 22:30:46,120 - INFO - Running preprocessor FuncProcessor, on stack of type uint8, True
2026-06-17 22:30:46,148 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function gaussian at 0x350e74720> args=[] kwargs={'sigma': 1.0}
2026-06-17 22:30:46,148 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:46,148 - INFO - Using Parallel with n_jobs=-1 for 93 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  32 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  41 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  50 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  61 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  72 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  86 out of  93 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  93 out of  93 | elapsed:    0.0s finished
2026-06-17 22:30:46,200 - INFO - Reshaped results to shape (3, 31, 512, 512)
2026-06-17 22:30:46,204 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-06-17 22:30:46,205 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-06-17 22:30:46,205 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:46,206 - INFO - Finished in state Completed()
2026-06-17 22:30:46,230 - INFO - Finished in state Completed()
2026-06-17 22:30:46,454 - INFO - Running preprocessor FuncProcessor, on stack of type float64, False
2026-06-17 22:30:46,679 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function adjust_gamma at 0x350e74220> args=[] kwargs={'gamma': 0.2}
2026-06-17 22:30:46,680 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:46,680 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.1s finished
2026-06-17 22:30:46,766 - INFO - Reshaped results to shape (3, 31, 512, 512)
2026-06-17 22:30:46,768 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-06-17 22:30:46,768 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-06-17 22:30:46,768 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:46,769 - INFO - Finished in state Completed()
2026-06-17 22:30:46,794 - INFO - Finished in state Completed()
2026-06-17 22:30:47,012 - INFO - Running preprocessor FuncProcessor, on stack of type float64, False
2026-06-17 22:30:47,231 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function adjust_sigmoid at 0x350e74360> args=[] kwargs={}
2026-06-17 22:30:47,231 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:47,231 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.1s finished
2026-06-17 22:30:47,306 - INFO - Reshaped results to shape (3, 31, 512, 512)
2026-06-17 22:30:47,308 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-06-17 22:30:47,308 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-06-17 22:30:47,308 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:47,309 - INFO - Finished in state Completed()
2026-06-17 22:30:47,333 - INFO - Finished in state Completed()
2026-06-17 22:30:47,554 - INFO - Running preprocessor Rescale, on stack of type float64, False
2026-06-17 22:30:47,775 - INFO - Running Rescale with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint8'> low=0.0 high=100.0
2026-06-17 22:30:47,775 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:47,775 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.0s finished
2026-06-17 22:30:47,825 - INFO - Reshaped results to shape (3, 31, 512, 512)
2026-06-17 22:30:47,826 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-06-17 22:30:47,826 - INFO - Metadata updated in Rescale: 1 key(s) changed
2026-06-17 22:30:47,826 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:47,827 - INFO - Finished in state Completed()
2026-06-17 22:30:47,897 - INFO - Finished in state Completed()
2026-06-17 22:30:47,926 - INFO - Running preprocessor FuncProcessor, on stack of type uint8, True
2026-06-17 22:30:47,954 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint16'> strict_axis=False func=<function max at 0x10df56070> args=[] kwargs={'axis': 'C'}
2026-06-17 22:30:47,954 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:30:47,954 - INFO - Mapped axis letters C to axis indices (0,)
2026-06-17 22:30:47,956 - INFO - Converted results to uint16
2026-06-17 22:30:47,957 - INFO - Dropping axes. New axes: ['Z', 'Y', 'X']
2026-06-17 22:30:47,958 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-06-17 22:30:47,958 - INFO - Metadata updated in FuncProcessor: 4 key(s) changed
2026-06-17 22:30:47,958 - INFO -   axes: ['C', 'Z', 'Y', 'X'] -> ['Z', 'Y', 'X']
2026-06-17 22:30:47,958 - INFO -   shape: (3, 31, 512, 512) -> (31, 512, 512)
2026-06-17 22:30:47,958 - INFO -   dims: <Dimensions [C: 3, Z: 31, Y: 512, X: 512]> -> <Dimensions [Z: 31, Y: 512, X: 512]>
2026-06-17 22:30:47,958 - INFO -   dim_order: CZYX -> ZYX
2026-06-17 22:30:47,959 - INFO - Finished in state Completed()
2026-06-17 22:30:47,985 - INFO - Finished in state Completed()
2026-06-17 22:30:47,986 - INFO - Finished in state Completed()
2026-06-17 22:30:48,104 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:30:48,229 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-4c7c-72b7-8000-b9ba3bf3d1a1/set_state "HTTP/1.1 201 Created"
2026-06-17 22:30:48,680 - INFO - Finished in state Completed()
2026-06-17 22:30:48,946 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:30:49,077 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-06-17 22:30:49,169 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:30:49,509 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:30:49,815 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-94dd-7a22-8000-2cf104b7e89a "HTTP/1.1 204 No Content"
2026-06-17 22:30:50,118 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-94dd-7a22-8000-2cf104b7e89a/set_state "HTTP/1.1 201 Created"
2026-06-17 22:30:50,196 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-94dd-7a22-8000-2cf104b7e89a "HTTP/1.1 200 OK"
2026-06-17 22:30:50,203 - INFO - Beginning subflow run 'autogenerated: TiledSegmentationFlow' for flow 'Workflow.run'
2026-06-17 22:30:50,204 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33585-94dd-7a22-8000-2cf104b7e89a
2026-06-17 22:30:50,255 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:30:50,266 - INFO - Resizing stack from (31, 512, 512) to [31, 128, 128]
2026-06-17 22:30:50,287 - INFO - Running preprocessor Resize, on stack of type uint16, True
2026-06-17 22:30:50,306 - INFO - Running Resize with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=(31, 128, 128) output_axes=None recompute_scale=True squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None width=128 height=128 order=1 preserve_range=True anti_aliasing=True
2026-06-17 22:30:50,306 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:30:50,306 - INFO - Using Parallel with n_jobs=2 for 31 iterations
2026-06-17 22:30:50,366 - INFO - Reshaped results to shape (31, 128, 128)
2026-06-17 22:30:50,366 - INFO - Updating metadata with new shape ratio: [1. 4. 4.]
2026-06-17 22:30:50,366 - INFO - Metadata updated in Resize: 4 key(s) changed
2026-06-17 22:30:50,367 - INFO -   physical_pixel_sizes: PhysicalPixelSizes(Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477) -> PhysicalPixelSizes(Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907)
2026-06-17 22:30:50,367 - INFO -   scale: Scale(T=None, C=None, Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477) -> Scale(T=None, C=None, Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907)
2026-06-17 22:30:50,367 - INFO -   shape: (31, 512, 512) -> (31, 128, 128)
2026-06-17 22:30:50,367 - INFO -   dims: <Dimensions [Z: 31, Y: 512, X: 512]> -> <Dimensions [Z: 31, Y: 128, X: 128]>
2026-06-17 22:30:50,368 - INFO - Finished in state Completed()
2026-06-17 22:30:50,370 - INFO - Finished in state Completed()
2026-06-17 22:30:50,371 - INFO - Finished in state Completed()
2026-06-17 22:30:50,378 - INFO - Running Tiler with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None factor=(3, 3) pad_width={-2: (0, 5), -1: (0, 5)} pad_kwargs={'mode': 'constant', 'constant_values': 0} alt_flip=False
2026-06-17 22:30:50,378 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:30:50,382 - INFO - Updating metadata with new shape ratio: [1.         0.33333333 0.33333333]
2026-06-17 22:30:50,382 - INFO - Metadata updated in Tiler: 2 key(s) changed
2026-06-17 22:30:50,382 - INFO -   shape: (31, 128, 128) -> (31, 399, 399)
2026-06-17 22:30:50,382 - INFO -   dims: <Dimensions [Z: 31, Y: 128, X: 128]> -> <Dimensions [Z: 31, Y: 399, X: 399]>
2026-06-17 22:30:50,384 - INFO - Finished in state Completed()

Using apple MPS device.

2026-06-17 22:30:52,389 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:30:55,451 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='./embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-06-17 22:30:55,452 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:30:55,452 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:30:55,452 - INFO - Set MPS memory fraction to 1.0
2026-06-17 22:30:55,467 - INFO - Using ./embeddings/714b9d9b0dc1b72d53e2cab31b7845ca644d7c9811fc761c81eacc48c5bacb0c for embeddings. img_slice.shape=(31, 399, 399)
progress: : 0it [00:00, ?it/s]
Segment slices: 100%|█████████████████████████████████████████████████████████████████| 31/31 [00:05<00:00,  5.52it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 19.43it/s]
2026-06-17 22:31:01,300 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-06-17 22:31:01,300 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-06-17 22:31:01,301 - INFO -   dims: <Dimensions [Z: 31, Y: 399, X: 399]> -> <Dimensions [Z: 31, Y: 399, X: 399]>
2026-06-17 22:31:01,302 - INFO - Finished in state Completed()
2026-06-17 22:31:01,328 - INFO - DEBUG: entered Relabeler.run
2026-06-17 22:31:01,549 - INFO - Finished in state Completed()
2026-06-17 22:31:01,566 - INFO - Finished in state Completed()
2026-06-17 22:31:01,608 - INFO - DEBUG: entered Relabeler.run
2026-06-17 22:31:01,806 - INFO - Finished in state Completed()
2026-06-17 22:31:01,820 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio']
2026-06-17 22:31:01,868 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio'] map_axes=False expand_coordinates=False
2026-06-17 22:31:01,868 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:31:01,881 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 1.2003733855185907, 1.2003733855185907), labels.shape=(31, 399, 399), channel_names=['Lobe']
2026-06-17 22:31:02,018 - INFO - Identified 161 regions, return as list
2026-06-17 22:31:02,019 - INFO - Finished in state Completed()
2026-06-17 22:31:02,020 - INFO - Finished in state Completed()
2026-06-17 22:31:02,057 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-yz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='aspect_ratio', axis=None, strict=True, preferred_input_type='numpy', range=(0.5, 1.0))]
2026-06-17 22:31:02,057 - INFO - Applying RegionFilter to a list
2026-06-17 22:31:02,130 - INFO - RegionFilter: len(accepted_regions)=11, len(removed_labels)=150
2026-06-17 22:31:02,131 - INFO - Finished in state Completed()
2026-06-17 22:31:02,181 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-06-17 22:31:02,181 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:02,222 - INFO - Finished in state Completed()
2026-06-17 22:31:02,237 - INFO - Finished in state Completed()
2026-06-17 22:31:02,238 - INFO - Finished in state Completed()
2026-06-17 22:31:02,325 - INFO - Running Untiler with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None factor=(3, 3)
2026-06-17 22:31:02,326 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:02,340 - INFO - factor=(3, 3), array.shape=(11, 31, 399, 399), vs.shape=(3, 11, 31, 399, 133), hs.shape=(3, 3, 11, 31, 133, 133), untiled.shape=(9, 11, 31, 133, 133)
2026-06-17 22:31:02,342 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-06-17 22:31:02,390 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=MaskStackBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None) area_calculator=MaskAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None) intersection_calculator=MaskIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None, memory_limit_mb=5120, prune_bboxes=False, dense_pair_fraction=1.01) metrics_calculators=[IoUMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='iou')] return_components=False triangle=2 output_type='np.ndarray' annotate=False
2026-06-17 22:31:02,391 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:31:02,459 - INFO - Finished in state Completed()
2026-06-17 22:31:02,463 - INFO - Finished in state Completed()
2026-06-17 22:31:02,466 - INFO - TiledSegmentationFlow: groups=[[0, 1, 2, 3, 5, 7, 8, 9, 10], [4, 6]]
2026-06-17 22:31:02,482 - INFO - Resizing stack from (31, 128, 128) to [31, 512, 512]
2026-06-17 22:31:02,490 - INFO - Running preprocessor Resize, on stack of type int64, True
2026-06-17 22:31:02,499 - INFO - Running Resize with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=(31, 512, 512) output_axes=None recompute_scale=True squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint16'> width=512 height=512 order=0 preserve_range=True anti_aliasing=False
2026-06-17 22:31:02,499 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:31:02,500 - INFO - Using Parallel with n_jobs=2 for 31 iterations
2026-06-17 22:31:02,542 - INFO - Reshaped results to shape (31, 512, 512)
2026-06-17 22:31:02,546 - INFO - Updating metadata with new shape ratio: [1.   0.25 0.25]
2026-06-17 22:31:02,546 - INFO - Metadata updated in Resize: 4 key(s) changed
2026-06-17 22:31:02,546 - INFO -   physical_pixel_sizes: PhysicalPixelSizes(Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907) -> PhysicalPixelSizes(Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477)
2026-06-17 22:31:02,546 - INFO -   scale: Scale(T=None, C=None, Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907) -> Scale(T=None, C=None, Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477)
2026-06-17 22:31:02,547 - INFO -   shape: (31, 128, 128) -> (31, 512, 512)
2026-06-17 22:31:02,547 - INFO -   dims: <Dimensions [Z: 31, Y: 128, X: 128]> -> <Dimensions [Z: 31, Y: 512, X: 512]>
2026-06-17 22:31:02,548 - INFO - Finished in state Completed()
2026-06-17 22:31:02,580 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:02,584 - INFO - Finished in state Completed()
2026-06-17 22:31:02,585 - INFO - Finished in state Completed()
2026-06-17 22:31:02,585 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio']
2026-06-17 22:31:02,628 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio'] map_axes=False expand_coordinates=False
2026-06-17 22:31:02,628 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-06-17 22:31:02,636 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Lobe']
2026-06-17 22:31:02,675 - INFO - Identified 2 regions, return as list
2026-06-17 22:31:02,676 - INFO - Finished in state Completed()
2026-06-17 22:31:02,677 - INFO - Finished in state Completed()
2026-06-17 22:31:02,703 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-yz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='aspect_ratio', axis=None, strict=True, preferred_input_type='numpy', range=(0.5, 1.0))]
2026-06-17 22:31:02,704 - INFO - Applying RegionFilter to a list
2026-06-17 22:31:02,886 - INFO - RegionFilter: len(accepted_regions)=2, len(removed_labels)=0
2026-06-17 22:31:02,887 - INFO - Finished in state Completed()
2026-06-17 22:31:02,929 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-06-17 22:31:02,929 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:02,932 - INFO - Finished in state Completed()
2026-06-17 22:31:02,953 - INFO - Finished in state Completed()
2026-06-17 22:31:02,955 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-06-17 22:31:03,183 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33585-94dd-7a22-8000-2cf104b7e89a/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:03,244 - INFO - Finished in state Completed()
2026-06-17 22:31:03,255 - INFO - Setting up PreprocessFlow with
2026-06-17 22:31:03,488 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:03,612 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-06-17 22:31:03,708 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:31:03,942 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:04,151 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-7da1-7643-8000-4512156f511f "HTTP/1.1 204 No Content"
2026-06-17 22:31:04,388 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-7da1-7643-8000-4512156f511f/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:04,507 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-7da1-7643-8000-4512156f511f "HTTP/1.1 200 OK"
2026-06-17 22:31:04,509 - INFO - Beginning subflow run 'autogenerated: PreprocessFlow' for flow 'Workflow.run'
2026-06-17 22:31:04,510 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33586-7da1-7643-8000-4512156f511f
2026-06-17 22:31:04,604 - INFO - Running PreprocessFlow with 0 processors
2026-06-17 22:31:04,606 - INFO - Finished in state Completed()
2026-06-17 22:31:04,702 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:04,969 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-7da1-7643-8000-4512156f511f/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:05,516 - INFO - Finished in state Completed()
2026-06-17 22:31:05,520 - INFO - Unstacked image data along 0 axis with index 0. Data shapes: [(31, 512, 512), (31, 512, 512), (31, 512, 512)]
2026-06-17 22:31:05,775 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:05,994 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-06-17 22:31:06,073 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:31:06,402 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:06,607 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-a373-7d8f-8000-bb925e163974 "HTTP/1.1 204 No Content"
2026-06-17 22:31:06,830 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:06,843 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-a373-7d8f-8000-bb925e163974/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:06,978 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-a373-7d8f-8000-bb925e163974 "HTTP/1.1 200 OK"
2026-06-17 22:31:06,979 - INFO - Beginning subflow run 'autogenerated: SegmentationFlow' for flow 'Workflow.mapped_run'
2026-06-17 22:31:06,979 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33586-a373-7d8f-8000-bb925e163974
2026-06-17 22:31:06,992 - INFO - SegmentationFlow _run: channel_names=['Scrib'], channel_axis=0, axes=['Z', 'Y', 'X']
2026-06-17 22:31:06,996 - INFO - SegmentationFlow _run: channel_names=['EdU'], channel_axis=0, axes=['Z', 'Y', 'X']
2026-06-17 22:31:06,999 - INFO - SegmentationFlow _run: channel_names=['Dpn'], channel_axis=0, axes=['Z', 'Y', 'X']
2026-06-17 22:31:07,091 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/2eaacb93-aa5c-40ac-9cd3-952883cbf6db "HTTP/1.1 200 OK"

Using apple MPS device.
Using apple MPS device.
Using apple MPS device.

2026-06-17 22:31:08,988 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:17,759 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='./embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-06-17 22:31:17,760 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:17,760 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:31:17,761 - INFO - Set MPS memory fraction to 1.0
2026-06-17 22:31:17,765 - INFO - Using ./embeddings/9316916d9ae9d1ba65e2637e3698268b42cf6f2a16301d0ce1775765c2d0340e for embeddings. img_slice.shape=(31, 512, 512)
progress: : 0it [00:00, ?it/s]
Segment slices:  16%|██████████▋                                                       | 5/31 [00:00<00:04,  5.83it/s]2026-06-17 22:31:18,820 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='./embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-06-17 22:31:18,820 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:18,821 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:31:18,821 - INFO - Set MPS memory fraction to 1.0
2026-06-17 22:31:18,825 - INFO - Using ./embeddings/d1fe2150ec13ee21684454b31417558f22ed2f8edc2d42ddb5e986feb108cea4 for embeddings. img_slice.shape=(31, 512, 512)
2026-06-17 22:31:18,959 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='./embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-06-17 22:31:18,960 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:18,961 - INFO - Found mps device: Apple Metal (MPS)
2026-06-17 22:31:18,961 - INFO - Set MPS memory fraction to 1.0
2026-06-17 22:31:18,966 - INFO - Using ./embeddings/7bc1b767f9f7eb5f2ca77fd3ef27b59d84767814f73c209b081c7639379bb24c for embeddings. img_slice.shape=(31, 512, 512)
progress: : 0it [00:00, ?it/s]███▊                                                     | 6/31 [00:01<00:04,  5.73it/s]
progress: : 0it [00:00, ?it/s]█████▉                                                   | 7/31 [00:01<00:04,  5.69it/s]

Segment slices:   3%|██▏                                                               | 1/31 [00:00<00:08,  3.60it/s]

Segment slices:  26%|█████████████████                                                 | 8/31 [00:01<00:06,  3.72it/s]
Segment slices:   6%|████▎                                                             | 2/31 [00:00<00:11,  2.57it/s]

Segment slices:  29%|███████████████████▏                                              | 9/31 [00:02<00:07,  3.05it/s]
Segment slices:  10%|██████▍                                                           | 3/31 [00:01<00:11,  2.38it/s]

Segment slices:  32%|████████████████████▉                                            | 10/31 [00:02<00:08,  2.59it/s]
Segment slices:  35%|███████████████████████                                          | 11/31 [00:03<00:08,  2.47it/s]

Segment slices:  13%|████████▌                                                         | 4/31 [00:01<00:12,  2.11it/s]
Segment slices:  16%|██████████▋                                                       | 5/31 [00:02<00:14,  1.86it/s]

Segment slices:  39%|█████████████████████████▏                                       | 12/31 [00:03<00:08,  2.16it/s]
Segment slices:  19%|████████████▊                                                     | 6/31 [00:02<00:11,  2.10it/s]

Segment slices:  42%|███████████████████████████▎                                     | 13/31 [00:04<00:08,  2.15it/s]
Segment slices:  23%|██████████████▉                                                   | 7/31 [00:03<00:12,  1.97it/s]

Segment slices:  45%|█████████████████████████████▎                                   | 14/31 [00:04<00:08,  2.09it/s]
Segment slices:  26%|█████████████████                                                 | 8/31 [00:03<00:11,  2.09it/s]

Segment slices:  48%|███████████████████████████████▍                                 | 15/31 [00:05<00:07,  2.11it/s]
Segment slices:  29%|███████████████████▏                                              | 9/31 [00:04<00:10,  2.11it/s]

Segment slices:  52%|█████████████████████████████████▌                               | 16/31 [00:05<00:07,  2.11it/s]
Segment slices:  32%|████████████████████▉                                            | 10/31 [00:04<00:09,  2.11it/s]

Segment slices:  55%|███████████████████████████████████▋                             | 17/31 [00:06<00:06,  2.12it/s]
Segment slices:  35%|███████████████████████                                          | 11/31 [00:05<00:09,  2.12it/s]

Segment slices:  58%|█████████████████████████████████████▋                           | 18/31 [00:06<00:06,  2.12it/s]
Segment slices:  39%|█████████████████████████▏                                       | 12/31 [00:05<00:08,  2.13it/s]

Segment slices:  61%|███████████████████████████████████████▊                         | 19/31 [00:07<00:05,  2.14it/s]
Segment slices:  65%|█████████████████████████████████████████▉                       | 20/31 [00:07<00:05,  2.14it/s]

Segment slices:  42%|███████████████████████████▎                                     | 13/31 [00:06<00:08,  2.12it/s]
Segment slices:  68%|████████████████████████████████████████████                     | 21/31 [00:07<00:04,  2.14it/s]

Segment slices:  45%|█████████████████████████████▎                                   | 14/31 [00:06<00:07,  2.13it/s]
Segment slices:  71%|██████████████████████████████████████████████▏                  | 22/31 [00:08<00:04,  2.14it/s]

Segment slices:  48%|███████████████████████████████▍                                 | 15/31 [00:07<00:07,  2.13it/s]
Segment slices:  74%|████████████████████████████████████████████████▏                | 23/31 [00:08<00:03,  2.15it/s]

Segment slices:  52%|█████████████████████████████████▌                               | 16/31 [00:07<00:07,  2.13it/s]
Segment slices:  77%|██████████████████████████████████████████████████▎              | 24/31 [00:09<00:02,  2.35it/s]

Segment slices:  55%|███████████████████████████████████▋                             | 17/31 [00:08<00:07,  1.95it/s]
Segment slices:  81%|████████████████████████████████████████████████████▍            | 25/31 [00:09<00:02,  2.20it/s]

Segment slices:  58%|█████████████████████████████████████▋                           | 18/31 [00:08<00:06,  2.12it/s]
Segment slices:  84%|██████████████████████████████████████████████████████▌          | 26/31 [00:10<00:02,  2.21it/s]

Segment slices:  61%|███████████████████████████████████████▊                         | 19/31 [00:09<00:05,  2.11it/s]
Segment slices:  87%|████████████████████████████████████████████████████████▌        | 27/31 [00:10<00:01,  2.17it/s]

Segment slices:  65%|█████████████████████████████████████████▉                       | 20/31 [00:09<00:05,  2.14it/s]
Segment slices:  90%|██████████████████████████████████████████████████████████▋      | 28/31 [00:11<00:01,  2.19it/s]

Segment slices:  68%|████████████████████████████████████████████                     | 21/31 [00:10<00:04,  2.16it/s]
Segment slices:  94%|████████████████████████████████████████████████████████████▊    | 29/31 [00:11<00:00,  2.18it/s]

Segment slices:  71%|██████████████████████████████████████████████▏                  | 22/31 [00:10<00:04,  2.14it/s]
Segment slices:  97%|██████████████████████████████████████████████████████████████▉  | 30/31 [00:12<00:00,  2.17it/s]

Segment slices:  74%|████████████████████████████████████████████████▏                | 23/31 [00:10<00:03,  2.16it/s]
Segment slices: 100%|█████████████████████████████████████████████████████████████████| 31/31 [00:12<00:00,  2.48it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.93it/s]
2026-06-17 22:31:30,530 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-06-17 22:31:30,531 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-06-17 22:31:30,531 - INFO -   dims: <Dimensions [Z: 31, Y: 512, X: 512]> -> <Dimensions [Z: 31, Y: 512, X: 512]>
2026-06-17 22:31:30,534 - INFO - Finished in state Completed()
2026-06-17 22:31:30,578 - INFO - DEBUG: entered Relabeler.run


Segment slices:  77%|██████████████████████████████████████████████████▎              | 24/31 [00:11<00:03,  2.16it/s]
Segment slices:  81%|████████████████████████████████████████████████████▍            | 25/31 [00:11<00:02,  2.26it/s]

Segment slices:  81%|████████████████████████████████████████████████████▍            | 25/31 [00:11<00:02,  2.52it/s]
Segment slices:  84%|██████████████████████████████████████████████████████▌          | 26/31 [00:11<00:02,  2.48it/s]

Segment slices:  84%|██████████████████████████████████████████████████████▌          | 26/31 [00:11<00:01,  2.68it/s]2026-06-17 22:31:31,258 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"

Segment slices:  87%|████████████████████████████████████████████████████████▌        | 27/31 [00:12<00:01,  2.66it/s]

Segment slices:  87%|████████████████████████████████████████████████████████▌        | 27/31 [00:12<00:01,  2.81it/s]
Segment slices:  90%|██████████████████████████████████████████████████████████▋      | 28/31 [00:12<00:01,  2.78it/s]

Segment slices:  90%|██████████████████████████████████████████████████████████▋      | 28/31 [00:12<00:01,  2.64it/s]
Segment slices:  94%|████████████████████████████████████████████████████████████▊    | 29/31 [00:12<00:00,  2.87it/s]2026-06-17 22:31:31,960 - INFO - Finished in state Completed()
2026-06-17 22:31:31,978 - INFO - Finished in state Completed()
2026-06-17 22:31:32,033 - INFO - DEBUG: entered Relabeler.run


Segment slices:  94%|████████████████████████████████████████████████████████████▊    | 29/31 [00:12<00:00,  3.05it/s]
Segment slices:  97%|██████████████████████████████████████████████████████████████▉  | 30/31 [00:13<00:00,  2.95it/s]

Segment slices:  97%|██████████████████████████████████████████████████████████████▉  | 30/31 [00:13<00:00,  3.07it/s]
Segment slices: 100%|█████████████████████████████████████████████████████████████████| 31/31 [00:13<00:00,  2.29it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.90it/s]
2026-06-17 22:31:32,673 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-06-17 22:31:32,674 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-06-17 22:31:32,674 - INFO -   dims: <Dimensions [Z: 31, Y: 512, X: 512]> -> <Dimensions [Z: 31, Y: 512, X: 512]>
2026-06-17 22:31:32,676 - INFO - Finished in state Completed()
2026-06-17 22:31:32,722 - INFO - DEBUG: entered Relabeler.run


Segment slices: 100%|█████████████████████████████████████████████████████████████████| 31/31 [00:13<00:00,  2.29it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.17it/s]
2026-06-17 22:31:32,820 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-06-17 22:31:32,821 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-06-17 22:31:32,821 - INFO -   dims: <Dimensions [Z: 31, Y: 512, X: 512]> -> <Dimensions [Z: 31, Y: 512, X: 512]>
2026-06-17 22:31:32,823 - INFO - Finished in state Completed()
2026-06-17 22:31:32,866 - INFO - DEBUG: entered Relabeler.run
2026-06-17 22:31:33,066 - INFO - Finished in state Completed()
2026-06-17 22:31:33,081 - INFO - Finished in state Completed()
2026-06-17 22:31:33,135 - INFO - DEBUG: entered Relabeler.run
2026-06-17 22:31:33,424 - INFO - Finished in state Completed()
2026-06-17 22:31:33,441 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-06-17 22:31:33,454 - INFO - Finished in state Completed()
2026-06-17 22:31:33,463 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:33,465 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-06-17 22:31:33,531 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-06-17 22:31:33,531 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:33,544 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['EdU']
2026-06-17 22:31:33,567 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-06-17 22:31:33,569 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:33,582 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Dpn']
2026-06-17 22:31:33,738 - INFO - Identified 122 regions, return as list
2026-06-17 22:31:33,742 - INFO - Finished in state Completed()
2026-06-17 22:31:33,748 - INFO - Finished in state Completed()
2026-06-17 22:31:33,788 - INFO - Identified 500 regions, return as list
2026-06-17 22:31:33,789 - INFO - Finished in state Completed()
2026-06-17 22:31:33,791 - INFO - Finished in state Completed()
2026-06-17 22:31:33,811 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-06-17 22:31:33,811 - INFO - Applying RegionFilter to a list
2026-06-17 22:31:33,812 - INFO - RegionFilter: len(accepted_regions)=92, len(removed_labels)=30
2026-06-17 22:31:33,814 - INFO - Finished in state Completed()
2026-06-17 22:31:33,840 - INFO - Finished in state Completed()
2026-06-17 22:31:33,851 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-06-17 22:31:33,851 - INFO - Applying RegionFilter to a list
2026-06-17 22:31:33,853 - INFO - RegionFilter: len(accepted_regions)=366, len(removed_labels)=134
2026-06-17 22:31:33,854 - INFO - Finished in state Completed()
2026-06-17 22:31:33,874 - INFO - Finished in state Completed()
2026-06-17 22:31:33,913 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-06-17 22:31:33,914 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:33,937 - INFO - DEBUG: entered Relabeler.run
2026-06-17 22:31:33,952 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-06-17 22:31:33,953 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:33,964 - INFO - Finished in state Completed()
2026-06-17 22:31:33,991 - INFO - Finished in state Completed()
2026-06-17 22:31:33,993 - INFO - Finished in state Completed()
2026-06-17 22:31:34,015 - INFO - Finished in state Completed()
2026-06-17 22:31:34,042 - INFO - Finished in state Completed()
2026-06-17 22:31:34,043 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>
DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-06-17 22:31:34,640 - INFO - Finished in state Completed()
2026-06-17 22:31:34,655 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-06-17 22:31:34,735 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-06-17 22:31:34,735 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:34,749 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Scrib']
2026-06-17 22:31:34,860 - INFO - Identified 325 regions, return as list
2026-06-17 22:31:34,862 - INFO - Finished in state Completed()
2026-06-17 22:31:34,864 - INFO - Finished in state Completed()
2026-06-17 22:31:34,915 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-06-17 22:31:34,915 - INFO - Applying RegionFilter to a list
2026-06-17 22:31:34,916 - INFO - RegionFilter: len(accepted_regions)=247, len(removed_labels)=78
2026-06-17 22:31:34,917 - INFO - Finished in state Completed()
2026-06-17 22:31:34,994 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-06-17 22:31:34,995 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:35,042 - INFO - Finished in state Completed()
2026-06-17 22:31:35,064 - INFO - Finished in state Completed()
2026-06-17 22:31:35,065 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-06-17 22:31:35,476 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33586-a373-7d8f-8000-bb925e163974/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:35,570 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:36,108 - INFO - Finished in state Completed('All states completed.')
2026-06-17 22:31:36,335 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:36,455 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-06-17 22:31:36,623 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-06-17 22:31:37,165 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-06-17 22:31:37,433 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33588-8d58-7d23-8000-148d263e6d5c "HTTP/1.1 204 No Content"
2026-06-17 22:31:37,622 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33588-8d58-7d23-8000-148d263e6d5c/set_state "HTTP/1.1 201 Created"
2026-06-17 22:31:37,731 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a33588-8d58-7d23-8000-148d263e6d5c "HTTP/1.1 200 OK"
2026-06-17 22:31:37,732 - INFO - Beginning subflow run 'autogenerated: AnalysisFlow' for flow 'Workflow.run'
2026-06-17 22:31:37,733 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a33588-8d58-7d23-8000-148d263e6d5c
2026-06-17 22:31:37,791 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['bbox', 'area', 'slice_id', 'cross_sectional_area', 'centroid', 'object_id', 'volume', 'stack_id', 'aspect_ratio', 'label'] map_axes=True expand_coordinates=False
2026-06-17 22:31:37,800 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:37,817 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-06-17 22:31:37,829 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Brain']
2026-06-17 22:31:37,841 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['bbox', 'area', 'slice_id', 'cross_sectional_area', 'centroid', 'object_id', 'volume', 'stack_id', 'aspect_ratio', 'label'] map_axes=True expand_coordinates=False
2026-06-17 22:31:37,842 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:37,850 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['bbox', 'area', 'slice_id', 'cross_sectional_area', 'centroid', 'object_id', 'volume', 'stack_id', 'aspect_ratio', 'label'] map_axes=True expand_coordinates=False
2026-06-17 22:31:37,851 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:37,855 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Lobe']
2026-06-17 22:31:37,859 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['bbox', 'area', 'slice_id', 'cross_sectional_area', 'centroid', 'object_id', 'volume', 'stack_id', 'aspect_ratio', 'label'] map_axes=True expand_coordinates=False
2026-06-17 22:31:37,859 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:37,867 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['EdU']
2026-06-17 22:31:37,870 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['bbox', 'area', 'slice_id', 'cross_sectional_area', 'centroid', 'object_id', 'volume', 'stack_id', 'aspect_ratio', 'label'] map_axes=True expand_coordinates=False
2026-06-17 22:31:37,870 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-06-17 22:31:37,873 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Scrib']
2026-06-17 22:31:37,884 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(31, 512, 512), channel_names=['Dpn']
2026-06-17 22:31:38,229 - INFO - Identified 92 regions, return as dataframe
2026-06-17 22:31:38,232 - INFO - Finished in state Completed()
2026-06-17 22:31:38,247 - INFO - Finished in state Completed()
2026-06-17 22:31:38,371 - INFO - Identified 247 regions, return as dataframe
2026-06-17 22:31:38,373 - INFO - Finished in state Completed()
2026-06-17 22:31:38,379 - INFO - Finished in state Completed()
2026-06-17 22:31:38,444 - INFO - Identified 2 regions, return as dataframe
2026-06-17 22:31:38,446 - INFO - Finished in state Completed()
2026-06-17 22:31:38,449 - INFO - Finished in state Completed()
2026-06-17 22:31:38,476 - INFO - Identified 366 regions, return as dataframe
2026-06-17 22:31:38,477 - INFO - Finished in state Completed()
2026-06-17 22:31:38,481 - INFO - Finished in state Completed()
2026-06-17 22:31:38,576 - INFO - Identified 1 regions, return as dataframe
2026-06-17 22:31:38,577 - INFO - Finished in state Completed()
2026-06-17 22:31:38,579 - INFO - Finished in state Completed()
2026-06-17 22:31:38,601 - INFO - Setting up overlap calculator for pairs: [('Brain', 'Lobe'), ('Brain', 'Scrib'), ('Brain', 'EdU'), ('Brain', 'Dpn'), ('Lobe', 'Brain'), ('Lobe', 'Scrib'), ('Lobe', 'EdU'), ('Lobe', 'Dpn'), ('Scrib', 'Brain'), ('Scrib', 'Lobe'), ('Scrib', 'EdU'), ('Scrib', 'Dpn'), ('EdU', 'Brain'), ('EdU', 'Lobe'), ('EdU', 'Scrib'), ('EdU', 'Dpn'), ('Dpn', 'Brain'), ('Dpn', 'Lobe'), ('Dpn', 'Scrib'), ('Dpn', 'EdU')]
2026-06-17 22:31:38,754 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,755 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,783 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,886 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,920 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,930 - INFO - Label intersection mode: linear: mask_stack_mb=62, pair_sparse_mb=50, f=1.00, max_bbox_frac=0.81, M=1,N=2
2026-06-17 22:31:38,932 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,935 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,935 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,939 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,963 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-06-17 22:31:38,997 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True

In [16]:
#combined_metadata

In [17]:
stackview.slice(np.concatenate(combined_labels, axis=-1))

HBox(children=(VBox(children=(VBox(children=(HBox(children=(VBox(children=(ImageWidget(height=512, width=2560)…

In [18]:
for k,v in measurements.items():
    print (k, type(v))
df=measurements["region_analyzer_all"].sort_values(["channel","label"])
df

region_analyzer: Brain <class 'pandas.core.frame.DataFrame'>
region_analyzer: Lobe <class 'pandas.core.frame.DataFrame'>
region_analyzer: Scrib <class 'pandas.core.frame.DataFrame'>
region_analyzer: EdU <class 'pandas.core.frame.DataFrame'>
region_analyzer: Dpn <class 'pandas.core.frame.DataFrame'>
overlap: Brain vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap: Brain vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap: Brain vs EdU <class 'pandas.core.frame.DataFrame'>
overlap: Brain vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap: Lobe vs Brain <class 'pandas.core.frame.DataFrame'>
overlap: Lobe vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap: Lobe vs EdU <class 'pandas.core.frame.DataFrame'>
overlap: Lobe vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap: Scrib vs Brain <class 'pandas.core.frame.DataFrame'>
overlap: Scrib vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap: Scrib vs EdU <class 'pandas.core.frame.DataFrame'>
overlap: Scrib vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap: EdU vs Brain <class 'pandas.core.frame.DataFrame'>
overlap: EdU vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap: EdU vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap: EdU vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap: Dpn vs Brain <class 'pandas.core.frame.DataFrame'>
overlap: Dpn vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap: Dpn vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap: Dpn vs EdU <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Brain vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Brain vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Brain vs EdU <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Brain vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Lobe vs Brain <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Lobe vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Lobe vs EdU <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Lobe vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Scrib vs Brain <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Scrib vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Scrib vs EdU <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Scrib vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap_filtered: EdU vs Brain <class 'pandas.core.frame.DataFrame'>
overlap_filtered: EdU vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap_filtered: EdU vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap_filtered: EdU vs Dpn <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Dpn vs Brain <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Dpn vs Lobe <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Dpn vs Scrib <class 'pandas.core.frame.DataFrame'>
overlap_filtered: Dpn vs EdU <class 'pandas.core.frame.DataFrame'>
overlap_aggregated: Brain vs Lobe <class 'pandas.core.series.Series'>
overlap_aggregated: Brain vs Scrib <class 'pandas.core.series.Series'>
overlap_aggregated: Brain vs EdU <class 'pandas.core.series.Series'>
overlap_aggregated: Brain vs Dpn <class 'pandas.core.series.Series'>
overlap_aggregated: Lobe vs Brain <class 'pandas.core.series.Series'>
overlap_aggregated: Lobe vs Scrib <class 'pandas.core.series.Series'>
overlap_aggregated: Lobe vs EdU <class 'pandas.core.series.Series'>
overlap_aggregated: Lobe vs Dpn <class 'pandas.core.series.Series'>
overlap_aggregated: Scrib vs Brain <class 'pandas.core.series.Series'>
overlap_aggregated: Scrib vs Lobe <class 'pandas.core.series.Series'>
overlap_aggregated: Scrib vs EdU <class 'pandas.core.series.Series'>
overlap_aggregated: Scrib vs Dpn <class 'pandas.core.series.Series'>
overlap_aggregated: EdU vs Brain <class 'pandas.core.series.Series'>
overlap_aggregated: EdU vs Lobe <class 'pandas.core.series.Series'>
overlap_aggregated: EdU vs Scrib <class 'pandas.core.series.Series'>
overlap_aggregated: EdU vs Dpn <class 'pandas.core.series.Series'>
overlap_aggregated: Dpn vs Brain <class 'pandas.core.series.Series'>
overlap_aggregated: Dpn vs Lobe <class 'pandas.core.series.Series'>
overlap_aggregated: Dpn vs Scrib <class 'pandas.core.series.Series'>
overlap_aggregated: Dpn vs EdU <class 'pandas.core.series.Series'>
region_analyzer_all <class 'pandas.core.frame.DataFrame'>
ios_global <class 'pandas.core.frame.DataFrame'>
containment_graph <class 'networkx.classes.digraph.DiGraph'>

,bbox-start-z,bbox-start-y,bbox-start-x,bbox-end-z,bbox-end-y,bbox-end-x,centroid-z,centroid-y,centroid-x,label,...,object_name,count Dpn,count EdU,count Lobe,count Scrib,lineage Brain,lineage Dpn,lineage EdU,lineage Lobe,lineage Scrib
object_id,,,,,,,,,,,,,,,,,,,,,
5773d5fd65b94620a859254931293715,0,0,52,31,508,468,-16.049514,82.509963,75.001211,1,...,Brain 1,90.0,183.0,2.0,147.0,NaN,NaN,NaN,NaN,NaN
9c1e77a1c81d435694b1f75c7cbc0f8e,0,90,177,7,113,192,-2.715642,30.322650,55.131900,1,...,Dpn 1,NaN,NaN,NaN,NaN,1.0,NaN,15.0,1.0,NaN
2fb607309f6d4e66839342c041090f45,0,108,200,6,137,223,-2.520354,36.195326,63.371667,2,...,Dpn 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90c6d222b6b64cdf96f5cff0f34cac63,0,117,221,9,138,246,-3.477915,38.225660,70.301012,3,...,Dpn 3,NaN,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN
fd041735bcda4bd0b84e256408228639,0,149,234,9,170,258,-3.942043,47.915481,73.290544,4,...,Dpn 4,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
003df068dbac4f1089a5481483b5b79c,30,344,411,31,391,460,-29.997854,109.242558,131.795382,243,...,Scrib 243,NaN,1.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN
b61734a2a3bc4109b27adadf1ffaf238,30,363,249,31,415,326,-29.997854,116.698411,85.848485,244,...,Scrib 244,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN
3f2da7f7c4f84cac80fdbbf326eb55a3,30,384,158,31,415,176,-29.997854,119.526690,49.991774,245,...,Scrib 245,1.0,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN
cf509b7f59344c36b313aeefd84d6161,30,445,351,31,460,365,-29.997854,135.753766,107.369937,246,...,Scrib 246,NaN,NaN,NaN,NaN,1.0,NaN,353.0,2.0,NaN
1ae282fc21e4408391ef8c34cd4c341d,30,440,375,31,469,405,-29.997854,136.383906,116.892512,247,...,Scrib 247,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN

# Query graph for object ancestor lineage

1. Subcellular cellular Dpn -> tissue lobe -> organ brain
2. Count descendants in each channel

In [20]:
dag = measurements["containment_graph"]

gqcfg = NXGraphQueryConfig(
    attributes=["descendant_counts", "ancestor_lineage"],
    filter_attribute="channel",
    filter_value="Lobe",
    include_attributes=["label", "channel"],
    lineage_value_attribute="label",
    output_type="dataframe",
)
gq = NXGraphQuery(gqcfg)
result = gq.run(dag, node=None)
df_counts = gq.format(result["descendant_counts"])
df_lineage = gq.format(result["ancestor_lineage"])
df = pd.concat([df_counts, df_lineage], axis=1)
df = df.loc[:, ~df.columns.duplicated()].sort_values(["label"])
df

2026-06-17 23:05:58,668 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:58,715 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:58,727 - INFO - Summarizing graph with config: classname='Configurable' package='vistiq.core' version=None command_group=None label_attribute='object_name' group_attribute='channel' filter_attribute='channel' filter_value='Lobe' include_attributes=['label', 'channel'] lineage_value_attribute='label' attributes=['descendant_counts', 'ancestor_lineage'] output_type='dataframe' output_index='object_id'
2026-06-17 23:05:58,727 - INFO - Node: None
2026-06-17 23:05:58,732 - INFO - Finished in state Completed()
2026-06-17 23:05:58,847 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:58,896 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:58,908 - INFO - Finished in state Completed()
2026-06-17 23:05:59,017 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:59,085 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-06-17 23:05:59,094 - INFO - Finished in state Completed()

,channel,label,count Dpn,count EdU,count Scrib,lineage Brain
object_id,,,,,,
e1ad228f9f7f48f7885b100e4ab20eff,Lobe,1,45,93,73,1
11d89d26ccd04f03a58753bb4279c260,Lobe,2,45,90,74,1

In [77]:
from pyvis.network import Network

net = Network(notebook=True, cdn_resources='in_line', bgcolor="#222222", font_color="white", select_menu=True)
net.barnes_hut()

# Convert the networkx object
net.from_nx(dag)
neighbor_map = net.get_adj_list()

# add neighbor data to node hover data
for node in net.nodes:
    node["title"] = node["object_name"] #+ "\n" +"  Neighbors:\n" + "\n".join(neighbor_map[node["id"]])
    #node["value"] = len(neighbor_map[node["object_name"]])

# Render
net.show("nx_graph.html")

nx_graph.html

In [ ]:
net.show_buttons(filter_=['physics'])

# Hierarchical label decomposition

# View in Napari

In [ ]:
import napari
viewer = napari.Viewer()

In [ ]:
scale = metadata["physical_pixel_sizes"]
channel_colors = ("green", "blue", "red")
nimg = img#np.expand_dims(img, axis=0)

# add brain label
viewer.add_labels(brain, name="Brain", scale=scale)

# add lobe labels
for ch, l, m in zip(metadata["channel_names"],cell_labels, cell_measurements):
    new_m = m.copy().reset_index()
    background = pd.DataFrame({c: [0] if c=="label" else [np.nan] for c in new_m.columns.to_list()})
    new_m = pd.concat([background, new_m], ignore_index=True)
    # print (new_m)
    viewer.add_labels(l, name=f"{ch}-Labels", features=new_m, scale=scale)

# add cell labels for each channel
ch_images, ch_metadata = unstack_image(img, metadata=metadata, axis="C", strict=False)
for name, c_img, color in zip(metadata["channel_names"], ch_images, channel_colors):
    viewer.add_image(c_img, name=f"{name}", scale=scale, colormap=color, blending="additive")

In [ ]:
dl1 = viewer.layers["Dpn-Labels-Lobe 1"]
dl2 = viewer.layers["Dpn-Labels-Lobe 2"]
print (np.intersect1d(np.unique(dl1.data), np.unique(dl2.data)))