In [1]:
from vistiq.io import ImageWriterConfig, ImageWriter, ImageLoader, ImageLoaderConfig, unstack_image
from vistiq.utils import ArrayIteratorConfig, check_device, resolve_futures 
from vistiq.core import Tiler, TilerConfig, Untiler, UntilerConfig
from vistiq.preprocess import FuncProcessor, FuncProcessorConfig, PreprocessFlow, PreprocessFlowConfig, ResizeConfig, Resize, RescaleConfig, Rescale, DoG, DoGConfig, PreprocessorConfig, Preprocessor
from vistiq.segment import RegionFilterConfig, RegionFilter, RangeFilterConfig, RangeFilter, RegionAnalyzerConfig, RegionAnalyzer 
from vistiq.segment import MicroSAMSegmenter, MicroSAMSegmenterConfig, MicroSAMMerger, MicroSAMMergerConfig
from vistiq.segment import TiledSegmentationFlow, TiledSegmentationFlowConfig, SegmentationFlow, SegmentationFlowConfig
from vistiq.analysis import CoincidenceDetectorConfig, CoincidenceDetector, AnalysisFlowConfig, AnalysisFlow, IoSMetricsCalculatorConfig
from vistiq.core import labels_to_masks
from vistiq.analysis.overlap import (
    OverlapCalculator,
    LabelOverlapCalculatorConfig,   # or BoxOverlapCalculatorConfig / MaskOverlapCalculatorConfig
    IoSMetricsCalculatorConfig,
    metrics_calculator_configs,
    region_map_from_dataframe,      # if using region maps from DataFrames
)
from vistiq.analysis import MatrixAggregator, MatrixAggregatorConfig, MatrixCombiner, MatrixCombinerConfig, SpatialScopeConfig
from vistiq.matrix.types import UPPER
from vistiq.matrix.types import UPPER_ND
from vistiq.segment.select import ValueFilter, ValueFilterConfig, TopKFilter, TopKFilterConfig
from vistiq.analysis import KnnAnalysis, KnnAnalysisConfig, RnnAnalysis, RnnAnalysisConfig
from vistiq.graph import GraphBuilder, GraphBuilderConfig, GraphQuery, GraphQueryConfig, GraphQueryFormatter, GraphQueryFormatterConfig
from vistiq.graph import HierarchyBuilderConfig

from prefect import flow, task
from prefect.task_runners import ProcessPoolTaskRunner
from prefect.futures import wait
from prefect.futures import resolve_futures_to_results
from scipy.ndimage import binary_dilation


import stackview
import os
import copy
import numpy as np
import math
import logging
import pandas as pd
import itertools

from typing import Any, List, Tuple
from pathlib import Path

FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
2026-07-06 15:54:58,068 - INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'

# Configure logger and check availability of accelerators

In [2]:
import vistiq
logger = logging.getLogger(vistiq.__name__)

logger.info(f"Available Torch accelerators: {check_device()}")

2026-07-06 15:54:58,927 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:54:58,927 - INFO - Available Torch accelerators: mps

# Load image

In [3]:
#path="/standard/vol191/siegristlab/Microsam_Segmentation/Conditional Split/control_24+48/DCP1/1_Dpn.tif"
#path="/standard/vol191/siegristlab/Microsam_Segmentation/24h/AkhGal4 x OR Susie/Scrib488 Dpn555 EdU 647/Raw files/Animal 1.lif"
path="../../cshl/two-lobes/Animal 1.lif"; scene_index=0
#path="../../cshl/Taylor_GWAS/high/189/dgrp.189.g1.animal1.lif"; scene_index=1
#path="../../cshl/Taylor_GWAS/high/189/dgrp.189.g1.animal2.lif"; scene_index=0
#path="/Users/khs3z/Documents/SDS_/projects/Siegrist/Microsam_Segmentation/24h/AkhGal4 x OR Susie/Scrib488 Dpn555 EdU 647/Animal 1.lif"

embedding_path = "../../embeddings"
#embedding_path = "/standard/vol191/siegristlab/Sagar/microsam/embeddings/"

In [4]:
ilc = ImageLoaderConfig(
    squeeze=True, 
    rename_channel={"Red": "Dpn", "Green": "Scrib", "Blue": "EdU"}, 
    scene_index=scene_index, 
    split_channels=False,
    #substack="Z:20-50"
)
img, metadata = ImageLoader(ilc).run(path)
metadata

2026-07-06 15:54:59,332 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 15:54:59,386 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 15:54:59,399 - INFO - Loading image from: ../../cshl/two-lobes/Animal 1.lif
2026-07-06 15:55:01,236 - INFO - Scenes found: ('Series001', 'Series002', 'Series003')
2026-07-06 15:55:01,363 - INFO - Loaded image: ../../cshl/two-lobes/Animal 1.lif scene=0 -> shape=(3, 93, 512, 512) dtype=uint8, channel_names=['Scrib', 'EdU', 'Dpn']
2026-07-06 15:55:01,365 - INFO - Loaded image with shape: (3, 93, 512, 512), dtype: uint8
2026-07-06 15:55:01,367 - INFO - Finished in state Completed()

{'scene_index': 0,
 'dim_order': 'CZYX',
 'axes': ['C', 'Z', 'Y', 'X'],
 'channel_names': ['Scrib', 'EdU', 'Dpn'],
 'channel_axis': 0,
 'shape': (3, 93, 512, 512),
 'dims': <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>,
 'pixel_unit': 'um',
 'scale': Scale(T=None, C=None, Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477),
 'physical_pixel_sizes': PhysicalPixelSizes(Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477)}

In [5]:
if "C" in metadata["axes"]:
    vimg = np.concatenate(np.unstack(img, axis=0), axis=-1)
else:
    vimg = img
stackview.slice(vimg)
#stackview.switch(img, colormap=["pure_green", "pure_blue", "pure_red"], toggleable=True)

HBox(children=(VBox(children=(VBox(children=(HBox(children=(VBox(children=(ImageWidget(height=512, width=1536)…

# Preprocess

In [6]:
tissue_ppcfg = PreprocessFlowConfig(
    processors = [
        RescaleConfig(
            low=2, 
            high=98, 
            dtype=np.uint8, 
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="skimage.filters.gaussian",
            kwargs={"sigma": 1.0},
            iterator_config=ArrayIteratorConfig(slice_def=(-2,-1)) # YX over each Z-plane and channel
        ),
        FuncProcessorConfig(
            func="skimage.exposure.adjust_gamma",
            kwargs={"gamma": 0.2},
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="skimage.exposure.adjust_sigmoid",
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        RescaleConfig(
            dtype=np.uint8, 
            iterator_config=ArrayIteratorConfig(slice_def=(-3,-2,-1)) # ZYX over each channel
        ),
        FuncProcessorConfig(
            func="numpy.max", 
            kwargs={"axis":("C")}, # Project all channels into one
            strict_axis=False,     # don't throw exception if the input is a single channel image already
            dtype=np.uint16,
        ),
        
        #FuncProcessorConfig(
        #    func="numpy.sum", 
        #    kwargs={"axis":("Z")}, # Project all channels into one
        #    strict_axis=False,     # don't throw exception if the input is a single channel image already
        #    #dtype=np.uint16,
        #),


    ]
)
#tissue_img, tissue_metadata = PreprocessFlow(tissue_ppcfg).run(img, metadata=metadata, workers=-1)
#metadata, tissue_metadata, tissue_img.shape

In [7]:
#tissue_metadata = copy.deepcopy(tissue_metadata)
#tissue_metadata["channel_names"] = ["Lobe"]
# segment tissue
#tissue_labels = TiledSegmentationFlow(tsfcfg).run(tissue_img, metadata=tissue_metadata, workers=2, verbose=0)

In [8]:
#stackview.slice(tissue_labels)

# Configuration for 3D Tissue Segmentation

In [9]:
mscfg = MicroSAMSegmenterConfig(
    iterator_config=ArrayIteratorConfig(slice_def=()),
    embedding_path=embedding_path,
)

rfcfg = RegionFilterConfig(
    filters=[
        #RangeFilterConfig(
        #    attribute="volume",
        #    range=(100000, np.inf),
        #),
        RangeFilterConfig(
            attribute="cross_sectional_area-xy", 
            range=(2000, np.inf),
        ),
        RangeFilterConfig(
            attribute="cross_sectional_area-xz", 
            range=(2000, np.inf),
        ),
        RangeFilterConfig(
            attribute="cross_sectional_area-yz", 
            range=(2000, np.inf),
        ),
        RangeFilterConfig(
            attribute="aspect_ratio", 
            range=(0.5, 1.0),
        ),
    ]
)

tsfcfg = TiledSegmentationFlowConfig(
    segmenter = mscfg,
    region_filter = rfcfg,
    tile_factor=(3,3),
    resize_factor=(0.25, 0.25),
    iou_threshold=0.5,
    consensus_threshold=0.75,
)

# Configuration for Region Analysis

In [10]:
racfg = RegionAnalyzerConfig(
    properties=["slice_annotations","volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
    iterator_config = ArrayIteratorConfig(slice_def=()),
    output_type="dataframe",
    map_axes=True,
)
ra = RegionAnalyzer(racfg)

# Configuration for Cell Segmentation

In [11]:
# specify preprocessing config for cells
cell_ppcfg = PreprocessFlowConfig(
    processors = [
        #DoGConfig(
        #    sigma_low=1, # 5, 
        #    sigma_high=2, #12, 
        #    normalize=True,
        #    iterator_config=ArrayIteratorConfig(slice_def=(-2,-1)) # YX over each Z focal plane and channel
        #)
    ]
)

In [12]:
# Specify segmentation config
mscfg = MicroSAMSegmenterConfig(
    iterator_config=ArrayIteratorConfig(slice_def=()),
    embedding_path=embedding_path,
    #gpu_fraction=0.3,
)

min_cell_radius = 2.0
max_cell_radius = 7.0
rfcfg = RegionFilterConfig(
    filters=[
        RangeFilterConfig(
            attribute="cross_sectional_area-xy", 
            range=(np.pi*min_cell_radius**2, np.pi*max_cell_radius**2)
        )
    ]
)

cell_sfcfg = SegmentationFlowConfig(
    segmenter = mscfg,
    region_filter = rfcfg,
)

In [13]:
@flow
def analyze_cells(labels: list[np.ndarray], metadata: list[dict[str, Any]]) -> list[pd.DataFrame]:
    print ([l.shape for l in labels])
    print ([m["channel_names"] for m in metadata])
    racfg = RegionAnalyzerConfig(
        properties=["volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
        iterator_config = ArrayIteratorConfig(slice_def=()),
        output_type="dataframe"
    )
    ra = RegionAnalyzer(racfg)

    measurements = ra.run.map(labels, metadata=metadata)

    cdcfg = CoincidenceDetectorConfig(
        method="ios",
        iterator_config=ArrayIteratorConfig(slice_def=()),
        mode="outline",
    )
    label_index_combinations = list(itertools.combinations(range(len(labels)), 2))
    l1 = [labels[c[0]] for c in label_index_combinations]
    l2 = [labels[c[1]] for c in label_index_combinations]
    sn = [(metadata[c[0]]["channel_names"][0], metadata[c[1]]["channel_names"][0]) for c in label_index_combinations]
    print (sn)
    #for la1, la2, sna in zip(l1,l2,sn): 
    cim = CoincidenceDetector(cdcfg).run.map(l1, l2, stack_names=sn)
    return measurements

In [14]:
acfg = AnalysisFlowConfig(
    region_analyzer = RegionAnalyzerConfig(
        properties=["volume", "centroid", "cross_sectional_area", "bbox", "aspect_ratio"],
        iterator_config = ArrayIteratorConfig(slice_def=()),
        output_type="dataframe",
        index_on="object_id",
        map_axes=True,
    ),
    #coincidence_detector = CoincidenceDetectorConfig(
    #    method=IoSMetricsCalculatorConfig(),
    #    iterator_config=ArrayIteratorConfig(slice_def=()),
    #    mode="outline",
    #),
    hierarchy_builder=HierarchyBuilderConfig(
        orphan_strategy="drop", #"group",
    ),
    overlap_calculator = LabelOverlapCalculatorConfig(
        metrics_calculators = [IoSMetricsCalculatorConfig()],
        output_type="dataframe",
        annotate=True,
        triangle=7,
    ),
    overlap_filter = ValueFilterConfig(
        ref_value=0.5,
        axis=0,
        operator=">",
        triangle=UPPER_ND, # has to be upper to align with downstream establishment of objeect hierarchies
        output="masked_values",
    ),
    overlap_aggregator = MatrixAggregatorConfig(
        operation="count",
        axis=1,
    ),
    knn_analysis = KnnAnalysisConfig(
        k=5,
        mode="homotypic",
        scope=SpatialScopeConfig(
            match={"channel": "Lobe"}
        )
    ),
    rnn_analysis = RnnAnalysisConfig(
        radius=25,
        mode="homotypic",
        scope=SpatialScopeConfig(
            match={"channel": "Lobe"}
        )
    ),
        
)

In [15]:
@flow
def full_pipeline(img_path, scene_index=0, outdir=".", embedding_path="embeddings"):
    # load image
    img, metadata = ImageLoader(ilc).run(img_path)
    
    # TISSUE - brain lobes
    # preprocess
    tissue_img, tissue_metadata = PreprocessFlow(tissue_ppcfg).run(img, metadata=metadata, workers=-1)
    # segment tissue
    tissue_labels = TiledSegmentationFlow(tsfcfg).run(tissue_img, metadata=tissue_metadata, workers=2, verbose=0)
    if tissue_labels.ndim == img.ndim-2:
        print ("USING 2D TISSUE MASK")
        print(f"tissue_labels.ndim={tissue_labels.ndim}, np.max(tissue_labels)={np.max(tissue_labels)}, tissue_labels.dtype={tissue_labels.dtype}, img.ndim={img.ndim}")
        fc = FuncProcessorConfig(
            func="numpy.repeat",
            args=[img.shape[1]],
            kwargs={"axis":(0,)}, # stck along Z axis
            strict_axis=False,     # don't throw exception if the input is a single channel image already
            output_dims={"Z": img.shape[-3], "Y": img.shape[-2], "X": img.shape[-1]},
            dtype=np.uint16,
        )
        arr = tissue_labels[np.newaxis, :, :]
        print (arr.shape)
        tissue_labels, tissue_metadata = FuncProcessor(fc).run(arr, metadata=tissue_metadata)
        print (f"{tissue_labels.shape}, {tissue_labels.dtype}, np.max(tissue_labels)={np.max(tissue_labels)}, {tissue_metadata}")
    else:
        print ("USING 3D TISSUE MASK")
    tissue_metadata = copy.deepcopy(tissue_metadata)
    tissue_metadata["channel_names"] = ["Lobe"]


    # BRAIN - all tissue combined
    #tissue_masks = labels_to_masks(tissue_labels)
    brain_mask = (tissue_labels>0).astype("uint16")
    focal_plane = len(tissue_labels)//2 
    brain_mask[focal_plane] = binary_dilation(brain_mask[focal_plane], iterations=1)
    brain_label = (brain_mask * 1).astype("uint16")
    brain_metadata = copy.deepcopy(tissue_metadata)

    # binary mask from segmented lobes
    #brain_mask = (tissue_labels > 0).astype("uint16")
    dcfg = FuncProcessorConfig(
        func="scipy.ndimage.binary_dilation",
        kwargs={"iterations": 1},  # XY pixels to grow
        iterator_config=ArrayIteratorConfig(slice_def=(-2, -1)),  # each YX plane
        normalize=False,
    )
    #brain_dilated, brain_metadata = FuncProcessor(dcfg).run(
    #    brain_mask,
    #    metadata=copy.deepcopy(tissue_metadata),
    #)
    #brain_label = brain_mask# brain_dilated#np.where(brain_dilated, 65535, 0).astype("uint16")
    brain_metadata["channel_names"] = ["Brain"]
    
    # CELLS
    # preprocess
    preprocessed, preprocessed_metadata = PreprocessFlow(cell_ppcfg).run(img, metadata=metadata)
    # split channels
    channels, channel_metadata = unstack_image(preprocessed, preprocessed_metadata, axis=metadata["channel_axis"], strict=False)
    # segment each channel separately
    #cell_labels = SegmentationFlow(cell_sfcfg).mapped_run(channels, metadata=channel_metadata, workers=1)
    cell_labels = [SegmentationFlow(cell_sfcfg).run(ch, metadata=ch_meta) for ch, ch_meta in zip(channels, channel_metadata)] 
    
    # Analyze CELLS and TISSUE
    # analyze regions in each channel separately
    combined_labels = [brain_label, tissue_labels, *cell_labels]
    combined_metadata = [brain_metadata, tissue_metadata, *channel_metadata]
    measurements = AnalysisFlow(acfg).run(combined_labels, metadata=combined_metadata)
    # measurements = analyze_cells([*cell_labels, lobe_labels, brain_label], metadata=[*channel_metadata, c_metadata, b_metadata])

    # save labels
    if outdir is None:
        outdir = Path(img_path).parent
    fname_stem = Path(img_path).stem
    imc = ImageWriterConfig(overwrite=True)
    outpaths = [os.path.join(outdir, f'{fname_stem}.scene-{meta.get("scene_index","")}.tif') for meta in combined_metadata]
    # print (outpaths)
    ImageWriter(imc).run.map(combined_labels, outpaths, metadata=combined_metadata)
    
    # make sure to resolve the futures to results
    return (
        resolve_futures(combined_labels),
        resolve_futures(combined_metadata),
        resolve_futures(measurements),
    )

In [16]:
combined_labels, combined_metadata, measurements = full_pipeline(path, scene_index=scene_index, outdir=".", embedding_path=embedding_path)

2026-07-06 15:55:36,650 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:55:36,944 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:55:37,155 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-8ca5-792b-8000-49c2c6757a58/set_state "HTTP/1.1 201 Created"
2026-07-06 15:55:37,376 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-8ca5-792b-8000-49c2c6757a58 "HTTP/1.1 200 OK"
2026-07-06 15:55:37,462 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 15:55:37,629 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 15:55:37,632 - INFO - Beginning flow run 'complex-lemur' for flow 'full-pipeline'
2026-07-06 15:55:37,637 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c083-8ca5-792b-8000-49c2c6757a58
2026-07-06 15:55:37,644 - INFO - Loading image from: ../../cshl/two-lobes/Animal 1.lif
2026-07-06 15:55:37,771 - INFO - Scenes found: ('Series001', 'Series002', 'Series003')
2026-07-06 15:55:37,909 - INFO - Loaded image: ../../cshl/two-lobes/Animal 1.lif scene=0 -> shape=(3, 93, 512, 512) dtype=uint8, channel_names=['Scrib', 'EdU', 'Dpn']
2026-07-06 15:55:37,912 - INFO - Loaded image with shape: (3, 93, 512, 512), dtype: uint8
2026-07-06 15:55:37,914 - INFO - Finished in state Completed()
2026-07-06 15:55:37,914 - INFO - Setting up PreprocessFlow with Rescale,FuncProcessor,FuncProcessor,FuncProcessor,Rescale,FuncProcessor
2026-07-06 15:55:38,262 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:55:38,373 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ece03cf4-776b-46e7-a39b-3fdfabe14f28 "HTTP/1.1 200 OK"
2026-07-06 15:55:38,390 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:55:38,598 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:55:38,850 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:55:39,078 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-ab8f-7ccb-8000-065fa41c77de "HTTP/1.1 204 No Content"
2026-07-06 15:55:39,273 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-ab8f-7ccb-8000-065fa41c77de/set_state "HTTP/1.1 201 Created"
2026-07-06 15:55:39,417 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-ab8f-7ccb-8000-065fa41c77de "HTTP/1.1 200 OK"
2026-07-06 15:55:39,420 - INFO - Beginning subflow run 'autogenerated: PreprocessFlow' for flow 'Workflow.run'
2026-07-06 15:55:39,422 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c083-ab8f-7ccb-8000-065fa41c77de
2026-07-06 15:55:39,536 - INFO - Running PreprocessFlow with 6 processors
2026-07-06 15:55:39,555 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/c32a815c-c449-48e0-a2fa-4b35e8784bee "HTTP/1.1 200 OK"
2026-07-06 15:55:39,618 - INFO - Running preprocessor Rescale, on stack of type uint8, True
2026-07-06 15:55:39,700 - INFO - Running Rescale with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint8'> low=2.0 high=98.0
2026-07-06 15:55:39,701 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:39,701 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
2026-07-06 15:55:39,995 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.4s finished
2026-07-06 15:55:40,117 - INFO - Reshaped results to shape (3, 93, 512, 512)
2026-07-06 15:55:40,118 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-07-06 15:55:40,118 - INFO - Metadata updated in Rescale: 1 key(s) changed
2026-07-06 15:55:40,118 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:40,120 - INFO - Finished in state Completed()
2026-07-06 15:55:40,468 - INFO - Finished in state Completed()
2026-07-06 15:55:40,558 - INFO - Running preprocessor FuncProcessor, on stack of type uint8, True
2026-07-06 15:55:40,641 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function gaussian at 0x349c56ca0> args=[] kwargs={'sigma': 1.0} output_dims=None
2026-07-06 15:55:40,642 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:40,642 - INFO - Using Parallel with n_jobs=-1 for 279 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  22 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  68 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 122 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 187 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 198 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 211 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 224 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 239 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 254 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 279 out of 279 | elapsed:    0.1s finished
2026-07-06 15:55:40,806 - INFO - Reshaped results to shape (3, 93, 512, 512)
2026-07-06 15:55:40,835 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-07-06 15:55:40,835 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-07-06 15:55:40,835 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:40,837 - INFO - Finished in state Completed()
2026-07-06 15:55:41,076 - INFO - Finished in state Completed()
2026-07-06 15:55:41,809 - INFO - Running preprocessor FuncProcessor, on stack of type float64, False
2026-07-06 15:55:42,092 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:55:42,471 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function adjust_gamma at 0x349c567a0> args=[] kwargs={'gamma': 0.2} output_dims=None
2026-07-06 15:55:42,471 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:42,472 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.2s finished
2026-07-06 15:55:42,779 - INFO - Reshaped results to shape (3, 93, 512, 512)
2026-07-06 15:55:42,792 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-07-06 15:55:42,792 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-07-06 15:55:42,793 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:42,794 - INFO - Finished in state Completed()
2026-07-06 15:55:42,920 - INFO - Finished in state Completed()
2026-07-06 15:55:43,646 - INFO - Running preprocessor FuncProcessor, on stack of type float64, False
2026-07-06 15:55:44,323 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None strict_axis=True func=<function adjust_sigmoid at 0x349c568e0> args=[] kwargs={} output_dims=None
2026-07-06 15:55:44,324 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:44,324 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
2026-07-06 15:55:44,397 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.3s finished
2026-07-06 15:55:44,713 - INFO - Reshaped results to shape (3, 93, 512, 512)
2026-07-06 15:55:44,729 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-07-06 15:55:44,729 - INFO - Metadata updated in FuncProcessor: 1 key(s) changed
2026-07-06 15:55:44,730 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:44,731 - INFO - Finished in state Completed()
2026-07-06 15:55:44,867 - INFO - Finished in state Completed()
2026-07-06 15:55:45,618 - INFO - Running preprocessor Rescale, on stack of type float64, False
2026-07-06 15:55:46,269 - INFO - Running Rescale with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-3, -2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint8'> low=0.0 high=100.0
2026-07-06 15:55:46,269 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:46,269 - INFO - Using Parallel with n_jobs=-1 for 3 iterations
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 14 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.3s finished
2026-07-06 15:55:46,621 - INFO - Reshaped results to shape (3, 93, 512, 512)
2026-07-06 15:55:46,622 - INFO - Updating metadata with new shape ratio: [1. 1. 1. 1.]
2026-07-06 15:55:46,622 - INFO - Metadata updated in Rescale: 1 key(s) changed
2026-07-06 15:55:46,622 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [C: 3, Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:46,668 - INFO - Finished in state Completed()
2026-07-06 15:55:46,853 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:55:46,914 - INFO - Finished in state Completed()
2026-07-06 15:55:46,998 - INFO - Running preprocessor FuncProcessor, on stack of type uint8, True
2026-07-06 15:55:47,078 - INFO - Running FuncProcessor with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=<class 'numpy.uint16'> strict_axis=False func=<function max at 0x119b40e30> args=[] kwargs={'axis': 'C'} output_dims=None
2026-07-06 15:55:47,078 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:55:47,078 - INFO - Mapped axis C to axis index 0
2026-07-06 15:55:47,085 - INFO - Converted results to uint16
2026-07-06 15:55:47,087 - INFO - Dropping axes. New axes: ['Z', 'Y', 'X']
2026-07-06 15:55:47,087 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-07-06 15:55:47,088 - INFO - Metadata updated in FuncProcessor: 4 key(s) changed
2026-07-06 15:55:47,088 - INFO -   axes: ['C', 'Z', 'Y', 'X'] -> ['Z', 'Y', 'X']
2026-07-06 15:55:47,088 - INFO -   dim_order: CZYX -> ZYX
2026-07-06 15:55:47,088 - INFO -   shape: (3, 93, 512, 512) -> (93, 512, 512)
2026-07-06 15:55:47,088 - INFO -   dims: <Dimensions [C: 3, Z: 93, Y: 512, X: 512]> -> <Dimensions [Z: 93, Y: 512, X: 512]>
2026-07-06 15:55:47,089 - INFO - Finished in state Completed()
2026-07-06 15:55:47,175 - INFO - Finished in state Completed()
2026-07-06 15:55:47,176 - INFO - Finished in state Completed()
2026-07-06 15:55:47,525 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c083-ab8f-7ccb-8000-065fa41c77de/set_state "HTTP/1.1 201 Created"
2026-07-06 15:55:48,467 - INFO - Finished in state Completed()
2026-07-06 15:55:48,658 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:55:48,753 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:55:48,841 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:55:49,042 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:55:49,053 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:55:49,185 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c084-4f36-7bd3-8000-68cf31e04b2d "HTTP/1.1 204 No Content"
2026-07-06 15:55:49,404 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c084-4f36-7bd3-8000-68cf31e04b2d/set_state "HTTP/1.1 201 Created"
2026-07-06 15:55:49,464 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c084-4f36-7bd3-8000-68cf31e04b2d "HTTP/1.1 200 OK"
2026-07-06 15:55:49,467 - INFO - Beginning subflow run 'autogenerated: TiledSegmentationFlow' for flow 'Workflow.run'
2026-07-06 15:55:49,469 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c084-4f36-7bd3-8000-68cf31e04b2d
2026-07-06 15:55:49,612 - INFO - Resizing stack from (93, 512, 512) to (93, 128, 128)
2026-07-06 15:55:49,669 - INFO - Running preprocessor Resize, on stack of type uint16, True
2026-07-06 15:55:49,726 - INFO - Running Resize with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=(93, 128, 128) output_axes=None recompute_scale=True squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None width=128 height=128 order=1 preserve_range=True anti_aliasing=True
2026-07-06 15:55:49,726 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-07-06 15:55:49,726 - INFO - Using Parallel with n_jobs=2 for 93 iterations
2026-07-06 15:55:49,862 - INFO - Reshaped results to shape (93, 128, 128)
2026-07-06 15:55:49,862 - INFO - Updating metadata with new shape ratio: [1. 4. 4.]
2026-07-06 15:55:49,862 - INFO - Metadata updated in Resize: 4 key(s) changed
2026-07-06 15:55:49,863 - INFO -   shape: (93, 512, 512) -> (93, 128, 128)
2026-07-06 15:55:49,863 - INFO -   scale: Scale(T=None, C=None, Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477) -> Scale(T=None, C=None, Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907)
2026-07-06 15:55:49,863 - INFO -   dims: <Dimensions [Z: 93, Y: 512, X: 512]> -> <Dimensions [Z: 93, Y: 128, X: 128]>
2026-07-06 15:55:49,863 - INFO -   physical_pixel_sizes: PhysicalPixelSizes(Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477) -> PhysicalPixelSizes(Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907)
2026-07-06 15:55:49,864 - INFO - Finished in state Completed()
2026-07-06 15:55:49,866 - INFO - Finished in state Completed()
2026-07-06 15:55:49,867 - INFO - Finished in state Completed()

Using apple MPS device.

2026-07-06 15:55:51,167 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:55:55,102 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='../../embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-07-06 15:55:55,102 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-07-06 15:55:55,103 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:55:55,103 - INFO - Set MPS memory fraction to 1.0
2026-07-06 15:55:55,148 - INFO - Using ../../embeddings/47b0a949323f1bcee23ae6da00b3f51585961740f1a8a72181f3d0d6f96f3856 for embeddings. img_slice.shape=(93, 399, 399)
progress: : 0it [00:00, ?it/s]
Segment slices: 100%|█████████████████████████████████████████████████████| 93/93 [00:15<00:00,  5.87it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.68it/s]
2026-07-06 15:56:11,725 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-07-06 15:56:11,725 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-07-06 15:56:11,726 - INFO -   dims: <Dimensions [Z: 93, Y: 399, X: 399]> -> <Dimensions [Z: 93, Y: 399, X: 399]>
2026-07-06 15:56:11,728 - INFO - Finished in state Completed()
2026-07-06 15:56:11,801 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:56:13,177 - INFO - Finished in state Completed()
2026-07-06 15:56:13,216 - INFO - Finished in state Completed()
2026-07-06 15:56:13,302 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:13,317 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:56:14,681 - INFO - Finished in state Completed()
2026-07-06 15:56:14,715 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio']
2026-07-06 15:56:14,845 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio'] map_axes=False expand_coordinates=False
2026-07-06 15:56:14,846 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-07-06 15:56:14,878 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 1.2003733855185907, 1.2003733855185907), labels.shape=(93, 399, 399), channel_names=['Scrib', 'EdU', 'Dpn']
2026-07-06 15:56:15,208 - INFO - Identified 370 regions, return as list
2026-07-06 15:56:15,209 - INFO - Finished in state Completed()
2026-07-06 15:56:15,211 - INFO - Finished in state Completed()
2026-07-06 15:56:15,303 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-yz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='aspect_ratio', axis=None, strict=True, preferred_input_type='numpy', range=(0.5, 1.0))]
2026-07-06 15:56:15,304 - INFO - Applying RegionFilter to a list
2026-07-06 15:56:15,403 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:15,557 - INFO - RegionFilter: len(accepted_regions)=18, len(removed_labels)=352
2026-07-06 15:56:15,558 - INFO - Finished in state Completed()
2026-07-06 15:56:15,689 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-07-06 15:56:15,690 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:56:15,802 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-07-06 15:56:15,849 - INFO - Finished in state Completed()
2026-07-06 15:56:15,850 - INFO - Finished in state Completed()
2026-07-06 15:56:16,249 - INFO - Running Untiler with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None factor=(3, 3)
2026-07-06 15:56:16,249 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:56:16,326 - INFO - factor=(3, 3), array.shape=(18, 93, 399, 399), vs.shape=(3, 18, 93, 399, 133), hs.shape=(3, 3, 18, 93, 133, 133), untiled.shape=(9, 18, 93, 133, 133)
2026-07-06 15:56:16,329 - INFO - Finished in state Completed()
2026-07-06 15:56:16,579 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=MaskStackBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None) area_calculator=MaskAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None) intersection_calculator=MaskIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='torch.Tensor', preferred_device=None, memory_limit_mb=5120, prune_bboxes=False, dense_pair_fraction=1.01) metrics_calculators=[IoUMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='iou')] return_components=False triangle=2 output_type='np.ndarray' annotate=False
2026-07-06 15:56:16,580 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:56:16,678 - INFO - Finished in state Completed()
2026-07-06 15:56:16,682 - INFO - Finished in state Completed()
2026-07-06 15:56:16,685 - INFO - TiledSegmentationFlow: groups=[[0, 2, 3, 5, 6, 8, 9, 13, 14], [1, 4, 7, 10, 11, 12, 15, 16, 17]]
2026-07-06 15:56:16,728 - INFO - Upsampling stack from (93, 128, 128) to (93, 512, 512)
2026-07-06 15:56:16,746 - INFO - Running Upsample with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=(-2, -1)) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=(93, 512, 512) output_axes=None recompute_scale=True squeeze=True split_axis=None split_channels=False rename_channel=None normalize=False dtype=None width=512 height=512 sigma=3.0
2026-07-06 15:56:16,746 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-07-06 15:56:16,746 - INFO - Using Parallel with n_jobs=2 for 93 iterations
2026-07-06 15:56:17,483 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:17,707 - INFO - Reshaped results to shape (93, 512, 512)
2026-07-06 15:56:17,717 - INFO - Updating metadata with new shape ratio: [1.   0.25 0.25]
2026-07-06 15:56:17,717 - INFO - Metadata updated in Upsample: 4 key(s) changed
2026-07-06 15:56:17,717 - INFO -   shape: (93, 128, 128) -> (93, 512, 512)
2026-07-06 15:56:17,717 - INFO -   scale: Scale(T=None, C=None, Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907) -> Scale(T=None, C=None, Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477)
2026-07-06 15:56:17,718 - INFO -   dims: <Dimensions [Z: 93, Y: 128, X: 128]> -> <Dimensions [Z: 93, Y: 512, X: 512]>
2026-07-06 15:56:17,718 - INFO -   physical_pixel_sizes: PhysicalPixelSizes(Z=-0.9999284782608696, Y=1.2003733855185907, X=1.2003733855185907) -> PhysicalPixelSizes(Z=-0.9999284782608696, Y=0.3000933463796477, X=0.3000933463796477)
2026-07-06 15:56:17,719 - INFO - Finished in state Completed()
2026-07-06 15:56:17,720 - INFO - Finished in state Completed()
2026-07-06 15:56:17,721 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio']
2026-07-06 15:56:18,169 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy', 'cross_sectional_area-xz', 'cross_sectional_area-yz', 'aspect_ratio'] map_axes=False expand_coordinates=False
2026-07-06 15:56:18,170 - INFO - StackProcessor.run: received workers=2 (type: <class 'int'>)
2026-07-06 15:56:18,230 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Scrib', 'EdU', 'Dpn']
2026-07-06 15:56:18,338 - INFO - Identified 2 regions, return as list
2026-07-06 15:56:18,339 - INFO - Finished in state Completed()
2026-07-06 15:56:18,340 - INFO - Finished in state Completed()
2026-07-06 15:56:18,583 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-yz', axis=None, strict=True, preferred_input_type='numpy', range=(2000.0, inf)), RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='aspect_ratio', axis=None, strict=True, preferred_input_type='numpy', range=(0.5, 1.0))]
2026-07-06 15:56:18,583 - INFO - Applying RegionFilter to a list
2026-07-06 15:56:18,980 - INFO - RegionFilter: len(accepted_regions)=2, len(removed_labels)=0
2026-07-06 15:56:18,981 - INFO - Finished in state Completed()

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-07-06 15:56:19,436 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-07-06 15:56:19,437 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:56:19,444 - INFO - Finished in state Completed()
2026-07-06 15:56:19,508 - INFO - Finished in state Completed()
2026-07-06 15:56:19,509 - INFO - Finished in state Completed()
2026-07-06 15:56:19,559 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:19,773 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c084-4f36-7bd3-8000-68cf31e04b2d/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:20,621 - INFO - Finished in state Completed()
2026-07-06 15:56:20,657 - INFO - Setting up PreprocessFlow with

USING 3D TISSUE MASK

2026-07-06 15:56:20,825 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:20,899 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:56:20,997 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:56:21,188 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:21,318 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-51aa-7769-8000-65e4752f0af7 "HTTP/1.1 204 No Content"
2026-07-06 15:56:21,494 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-51aa-7769-8000-65e4752f0af7/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:21,567 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-51aa-7769-8000-65e4752f0af7 "HTTP/1.1 200 OK"
2026-07-06 15:56:21,570 - INFO - Beginning subflow run 'autogenerated: PreprocessFlow' for flow 'Workflow.run'
2026-07-06 15:56:21,571 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c086-51aa-7769-8000-65e4752f0af7
2026-07-06 15:56:21,653 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:21,686 - INFO - Running PreprocessFlow with 0 processors
2026-07-06 15:56:21,687 - INFO - Finished in state Completed()
2026-07-06 15:56:21,928 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-51aa-7769-8000-65e4752f0af7/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:22,599 - INFO - Finished in state Completed()
2026-07-06 15:56:22,600 - INFO - Unstacked image data along 0 axis with index 0. Data shapes: [(93, 512, 512), (93, 512, 512), (93, 512, 512)]
2026-07-06 15:56:22,806 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:22,904 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:56:22,997 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:56:23,309 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:23,503 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-720c-751a-8000-f87ea9b6a746 "HTTP/1.1 204 No Content"
2026-07-06 15:56:23,670 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-720c-751a-8000-f87ea9b6a746/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:23,737 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-720c-751a-8000-f87ea9b6a746 "HTTP/1.1 200 OK"
2026-07-06 15:56:23,741 - INFO - Beginning subflow run 'autogenerated: SegmentationFlow' for flow 'Workflow.run'
2026-07-06 15:56:23,742 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c086-720c-751a-8000-f87ea9b6a746
2026-07-06 15:56:23,764 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:23,795 - INFO - SegmentationFlow _run: channel_names=['Scrib'], channel_axis=0, axes=['Z', 'Y', 'X']

Using apple MPS device.

2026-07-06 15:56:25,958 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:29,379 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='../../embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-07-06 15:56:29,380 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:56:29,380 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:56:29,380 - INFO - Set MPS memory fraction to 1.0
2026-07-06 15:56:29,391 - INFO - Using ../../embeddings/08c40783d30cc1b71264cf5e599bbf7f6fa42d7f8bd59d144921deb31047d48e for embeddings. img_slice.shape=(93, 512, 512)
progress: : 0it [00:00, ?it/s]
Segment slices: 100%|█████████████████████████████████████████████████████| 93/93 [00:16<00:00,  5.81it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.78it/s]
2026-07-06 15:56:46,367 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-07-06 15:56:46,368 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-07-06 15:56:46,368 - INFO -   dims: <Dimensions [Z: 93, Y: 512, X: 512]> -> <Dimensions [Z: 93, Y: 512, X: 512]>
2026-07-06 15:56:46,371 - INFO - Finished in state Completed()
2026-07-06 15:56:46,492 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:56:48,163 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:50,719 - INFO - Finished in state Completed()
2026-07-06 15:56:50,766 - INFO - Finished in state Completed()
2026-07-06 15:56:50,923 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:56:52,329 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:55,076 - INFO - Finished in state Completed()
2026-07-06 15:56:55,127 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-07-06 15:56:55,362 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-07-06 15:56:55,362 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:56:55,405 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Scrib']
2026-07-06 15:56:55,654 - INFO - Identified 648 regions, return as list
2026-07-06 15:56:55,655 - INFO - Finished in state Completed()
2026-07-06 15:56:55,656 - INFO - Finished in state Completed()
2026-07-06 15:56:55,803 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-07-06 15:56:55,803 - INFO - Applying RegionFilter to a list
2026-07-06 15:56:55,805 - INFO - RegionFilter: len(accepted_regions)=457, len(removed_labels)=191
2026-07-06 15:56:55,806 - INFO - Finished in state Completed()
2026-07-06 15:56:56,030 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-07-06 15:56:56,030 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-07-06 15:56:56,183 - INFO - Finished in state Completed()
2026-07-06 15:56:56,247 - INFO - Finished in state Completed()
2026-07-06 15:56:56,249 - INFO - Finished in state Completed()
2026-07-06 15:56:56,422 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:56:56,506 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c086-720c-751a-8000-f87ea9b6a746/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:56,883 - INFO - Finished in state Completed()
2026-07-06 15:56:57,060 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:57,140 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:56:57,228 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:56:57,436 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:56:57,583 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c088-9587-755e-8000-554241b91b66 "HTTP/1.1 204 No Content"
2026-07-06 15:56:57,808 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c088-9587-755e-8000-554241b91b66/set_state "HTTP/1.1 201 Created"
2026-07-06 15:56:57,937 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c088-9587-755e-8000-554241b91b66 "HTTP/1.1 200 OK"
2026-07-06 15:56:57,943 - INFO - Beginning subflow run 'autogenerated: SegmentationFlow' for flow 'Workflow.run'
2026-07-06 15:56:57,944 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c088-9587-755e-8000-554241b91b66
2026-07-06 15:56:57,999 - INFO - SegmentationFlow _run: channel_names=['EdU'], channel_axis=0, axes=['Z', 'Y', 'X']

Using apple MPS device.

2026-07-06 15:56:58,489 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:57:03,957 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='../../embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-07-06 15:57:03,958 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:57:03,958 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:57:03,958 - INFO - Set MPS memory fraction to 1.0
2026-07-06 15:57:03,969 - INFO - Using ../../embeddings/f9992f6d4a5c4290ddd060675b0a6ed6cbf07839f93523a172763211d6254d43 for embeddings. img_slice.shape=(93, 512, 512)
progress: : 0it [00:00, ?it/s]
Segment slices: 100%|█████████████████████████████████████████████████████| 93/93 [00:15<00:00,  6.02it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.47it/s]
2026-07-06 15:57:20,000 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-07-06 15:57:20,000 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-07-06 15:57:20,000 - INFO -   dims: <Dimensions [Z: 93, Y: 512, X: 512]> -> <Dimensions [Z: 93, Y: 512, X: 512]>
2026-07-06 15:57:20,002 - INFO - Finished in state Completed()
2026-07-06 15:57:20,124 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:57:20,661 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:57:25,939 - INFO - Finished in state Completed()
2026-07-06 15:57:25,979 - INFO - Finished in state Completed()
2026-07-06 15:57:26,132 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:57:26,770 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:57:32,009 - INFO - Finished in state Completed()
2026-07-06 15:57:32,049 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-07-06 15:57:32,286 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-07-06 15:57:32,287 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:57:32,319 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['EdU']
2026-07-06 15:57:32,592 - INFO - Identified 902 regions, return as list
2026-07-06 15:57:32,593 - INFO - Finished in state Completed()
2026-07-06 15:57:32,595 - INFO - Finished in state Completed()
2026-07-06 15:57:32,731 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-07-06 15:57:32,731 - INFO - Applying RegionFilter to a list
2026-07-06 15:57:32,734 - INFO - RegionFilter: len(accepted_regions)=659, len(removed_labels)=243
2026-07-06 15:57:32,735 - INFO - Finished in state Completed()
2026-07-06 15:57:32,964 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-07-06 15:57:32,964 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:57:33,040 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-07-06 15:57:33,100 - INFO - Finished in state Completed()
2026-07-06 15:57:33,167 - INFO - Finished in state Completed()
2026-07-06 15:57:33,169 - INFO - Finished in state Completed()
2026-07-06 15:57:33,398 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c088-9587-755e-8000-554241b91b66/set_state "HTTP/1.1 201 Created"
2026-07-06 15:57:34,088 - INFO - Finished in state Completed()
2026-07-06 15:57:34,256 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:57:34,335 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:57:34,450 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:57:34,656 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:57:34,771 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08a-e900-7a69-8000-d8694338c949 "HTTP/1.1 204 No Content"
2026-07-06 15:57:34,937 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08a-e900-7a69-8000-d8694338c949/set_state "HTTP/1.1 201 Created"
2026-07-06 15:57:35,058 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08a-e900-7a69-8000-d8694338c949 "HTTP/1.1 200 OK"
2026-07-06 15:57:35,061 - INFO - Beginning subflow run 'autogenerated: SegmentationFlow' for flow 'Workflow.run'
2026-07-06 15:57:35,062 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c08a-e900-7a69-8000-d8694338c949
2026-07-06 15:57:35,120 - INFO - SegmentationFlow _run: channel_names=['Dpn'], channel_axis=0, axes=['Z', 'Y', 'X']
2026-07-06 15:57:35,284 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"

Using apple MPS device.

2026-07-06 15:57:37,391 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:57:41,181 - INFO - Running MicroSAMSegmenter with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='processes' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None model_type='vit_l_lm' checkpoint=None embedding_path='../../embeddings' pred_iou_thresh=0.88 stability_score_thresh=0.95 box_nms_thresh=0.7 crop_nms_thresh=0.7 min_mask_region_area=0 output_mode='instance_segmentation' with_background=True device=None device_no=0 gpu_fraction=1.0
2026-07-06 15:57:41,181 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:57:41,182 - INFO - Found mps device: Apple Metal (MPS)
2026-07-06 15:57:41,182 - INFO - Set MPS memory fraction to 1.0
2026-07-06 15:57:41,192 - INFO - Using ../../embeddings/040b65c384168bc8f1a3159e9edd9b467bea0a257574cd8e748d42ec0051c737 for embeddings. img_slice.shape=(93, 512, 512)
progress: : 0it [00:00, ?it/s]
Segment slices: 100%|█████████████████████████████████████████████████████| 93/93 [00:15<00:00,  6.03it/s]
Merge segmentation: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.43it/s]
2026-07-06 15:57:57,184 - INFO - Updating metadata with new shape ratio: [1. 1. 1.]
2026-07-06 15:57:57,184 - INFO - Metadata updated in MicroSAMSegmenter: 1 key(s) changed
2026-07-06 15:57:57,184 - INFO -   dims: <Dimensions [Z: 93, Y: 512, X: 512]> -> <Dimensions [Z: 93, Y: 512, X: 512]>
2026-07-06 15:57:57,185 - INFO - Finished in state Completed()
2026-07-06 15:57:57,312 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:57:57,647 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:57:59,064 - INFO - Finished in state Completed()
2026-07-06 15:57:59,094 - INFO - Finished in state Completed()
2026-07-06 15:57:59,237 - INFO - DEBUG: entered Relabeler.run
2026-07-06 15:57:59,750 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:58:00,996 - INFO - Finished in state Completed()
2026-07-06 15:58:01,026 - INFO - Creating RegionAnalyzer for region filter with properties: ['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy']
2026-07-06 15:58:01,262 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='list' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='label' properties=['label', 'object_id', 'slice_id', 'stack_id', 'centroid', 'cross_sectional_area-xy'] map_axes=False expand_coordinates=False
2026-07-06 15:58:01,263 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:01,291 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Dpn']
2026-07-06 15:58:01,405 - INFO - Identified 273 regions, return as list
2026-07-06 15:58:01,406 - INFO - Finished in state Completed()
2026-07-06 15:58:01,407 - INFO - Finished in state Completed()
2026-07-06 15:58:01,532 - INFO - Running RegionFilter with config: classname='Configurable' package='vistiq.core' version=None command_group=None filters=[RangeFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute='cross_sectional_area-xy', axis=None, strict=True, preferred_input_type='numpy', range=(12.566370614359172, 153.93804002589985))]
2026-07-06 15:58:01,532 - INFO - Applying RegionFilter to a list
2026-07-06 15:58:01,533 - INFO - RegionFilter: len(accepted_regions)=204, len(removed_labels)=69
2026-07-06 15:58:01,534 - INFO - Finished in state Completed()
2026-07-06 15:58:01,769 - INFO - Running LabelRemover with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='stack' output_shape=None output_axes=None recompute_scale=False squeeze=False split_axis=None split_channels=False rename_channel=None remap=True
2026-07-06 15:58:01,769 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)

DEBUG: entered LabelRemover.run
DEBUG: region_properties type = <class 'list'>

2026-07-06 15:58:01,884 - INFO - Finished in state Completed()
2026-07-06 15:58:01,892 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:58:01,947 - INFO - Finished in state Completed()
2026-07-06 15:58:01,948 - INFO - Finished in state Completed()
2026-07-06 15:58:02,205 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08a-e900-7a69-8000-d8694338c949/set_state "HTTP/1.1 201 Created"
2026-07-06 15:58:03,199 - INFO - Finished in state Completed()
2026-07-06 15:58:03,430 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/task_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:58:03,642 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/filter "HTTP/1.1 200 OK"
2026-07-06 15:58:03,747 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flows/ "HTTP/1.1 200 OK"
2026-07-06 15:58:03,962 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:58:04,029 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/ "HTTP/1.1 201 Created"
2026-07-06 15:58:04,128 - INFO - HTTP Request: PATCH https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08c-be25-7c9a-8000-31fcdcfcead2 "HTTP/1.1 204 No Content"
2026-07-06 15:58:04,366 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08c-be25-7c9a-8000-31fcdcfcead2/set_state "HTTP/1.1 201 Created"
2026-07-06 15:58:04,433 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/flow_runs/06a4c08c-be25-7c9a-8000-31fcdcfcead2 "HTTP/1.1 200 OK"
2026-07-06 15:58:04,436 - INFO - Beginning subflow run 'autogenerated: AnalysisFlow' for flow 'Workflow.run'
2026-07-06 15:58:04,438 - INFO - View at https://app.prefect.cloud/account/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspace/0aefefee-2869-4637-89ac-c510d86c639e/runs/flow-run/06a4c08c-be25-7c9a-8000-31fcdcfcead2
2026-07-06 15:58:04,441 - INFO - Running analysis flow with config: classname='Configurable' package='vistiq.core' version=None command_group=None region_analyzer=RegionAnalyzerConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, iterator_config=ArrayIteratorConfig(classname=None, slice_def=()), batch_size=10, preferred_backend='threads', tile_shape=None, output_type='dataframe', output_shape=None, output_axes=None, recompute_scale=False, squeeze=True, split_axis=None, split_channels=False, rename_channel=None, index_on='object_id', properties=['label', 'stack_id', 'slice_id', 'object_id', 'centroid', 'cross_sectional_area', 'bbox', 'aspect_ratio', 'area'], map_axes=True, expand_coordinates=False) distance_calculator=None coincidence_detector=None overlap_calculator=LabelOverlapCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None), area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None), intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25), metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')], return_components=False, triangle=7, output_type='dataframe', annotate=True) overlap_filter=ValueFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute=None, axis=0, strict=True, preferred_input_type='torch.Tensor', ignore_nan=True, triangle=4, preferred_device=None, output='masked_values', ref_value=0.5, operator='>') overlap_aggregator=MatrixAggregatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, operation='count', axis=1, ignore_nan=True, triangle=7, preferred_input_type='torch.Tensor', preferred_device=None) matrix_combiner=MatrixCombinerConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, fill_value=nan, symmetrize=True, triangle=5) hierarchical_matrix=HierarchicalMatrixConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, rank_attribute='volume', threshold=0.5, parent_strategy='smallest_enclosing', orphan_strategy='drop', orphan_groupby=None, orphan_attach='separate_root', synthetic_weight=1.0, orphan_node={'name': 'Orphans', 'synthetic': True}, all_node={'name': 'all', 'synthetic': True}) graph_builder=GraphBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, edge_attribute='ios', synthetic_attribute='synthetic', graph_type='directed') graph_query=GraphQueryConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, label_attribute='object_name', group_attribute='channel', filter_attribute='channel', filter_value=None, include_attributes=['label', 'channel'], lineage_value_attribute='label', weight_attribute='ios', neighbor_analysis=None, neighbor_k=None, neighbor_radius=None, source_filter=None, target_filter=None, source_nodes=None, predecessor_match=None, seed_nodes=None, attributes=['descendant_counts', 'ancestor_lineage'], output_type='dataframe', output_index='object_id') graph_exporter=GraphExporterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, index='object_id', columns=None, dropna_cols=False, dropna_rows=False, exclude_synthetic=False) spatial_graph_query=GraphQueryConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, label_attribute='object_name', group_attribute='channel', filter_attribute=None, filter_value=None, include_attributes=[], lineage_value_attribute='label', weight_attribute='distance', neighbor_analysis=None, neighbor_k=None, neighbor_radius=None, source_filter=None, target_filter=None, source_nodes=None, predecessor_match=None, seed_nodes=None, attributes=['neighbor_summary'], output_type='dataframe', output_index='object_id') knn_analysis=KnnAnalysisConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, mode='homotypic', grouping_attribute='channel', scope=SpatialScopeConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, match={'channel': 'Lobe'}, exclude=None, auto_root=False), centroid='centroid', axes=None, graph_exporter=GraphExporterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, index='object_id', columns=None, dropna_cols=False, dropna_rows=False, exclude_synthetic=True), distance_calculator=DistanceCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, annotate=True, output_type='dataframe', preferred_input_type='torch.Tensor', preferred_device=None, method='euclidean', minkowski_p=3.0), k=5, knn_filter=TopKFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute=None, axis=1, strict=True, preferred_input_type='torch.Tensor', ignore_nan=True, triangle=6, preferred_device=None, output='masked_values', k=5, largest=False, sort=False), graph_builder=GraphBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, edge_attribute='distance', synthetic_attribute='synthetic', graph_type='directed')) rnn_analysis=RnnAnalysisConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, mode='homotypic', grouping_attribute='channel', scope=SpatialScopeConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, match={'channel': 'Lobe'}, exclude=None, auto_root=False), centroid='centroid', axes=None, graph_exporter=GraphExporterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, index='object_id', columns=None, dropna_cols=False, dropna_rows=False, exclude_synthetic=True), distance_calculator=DistanceCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, annotate=True, output_type='dataframe', preferred_input_type='torch.Tensor', preferred_device=None, method='euclidean', minkowski_p=3.0), radius=25.0, rnn_filter=ValueFilterConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, attribute=None, axis=None, strict=True, preferred_input_type='torch.Tensor', ignore_nan=True, triangle=6, preferred_device=None, output='masked_values', ref_value=None, operator='<='), graph_builder=GraphBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, edge_attribute='distance', synthetic_attribute='synthetic', graph_type='directed')) spatial_scope=SpatialScopeConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, match=None, exclude=None, auto_root=False) auto_join=True pairing_mode='permutations'
2026-07-06 15:58:04,442 - INFO - Number of labels: 5
2026-07-06 15:58:04,594 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['aspect_ratio', 'stack_id', 'bbox', 'centroid', 'object_id', 'slice_id', 'area', 'label', 'cross_sectional_area', 'volume'] map_axes=True expand_coordinates=False
2026-07-06 15:58:04,594 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:04,666 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Brain']
2026-07-06 15:58:04,745 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['aspect_ratio', 'stack_id', 'bbox', 'centroid', 'object_id', 'slice_id', 'area', 'label', 'cross_sectional_area', 'volume'] map_axes=True expand_coordinates=False
2026-07-06 15:58:04,745 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:04,769 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['aspect_ratio', 'stack_id', 'bbox', 'centroid', 'object_id', 'slice_id', 'area', 'label', 'cross_sectional_area', 'volume'] map_axes=True expand_coordinates=False
2026-07-06 15:58:04,769 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:04,779 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Lobe']
2026-07-06 15:58:04,789 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['aspect_ratio', 'stack_id', 'bbox', 'centroid', 'object_id', 'slice_id', 'area', 'label', 'cross_sectional_area', 'volume'] map_axes=True expand_coordinates=False
2026-07-06 15:58:04,790 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:04,803 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Scrib']
2026-07-06 15:58:04,810 - INFO - Running RegionAnalyzer with config: classname='Configurable' package='vistiq.core' version=None command_group=None iterator_config=ArrayIteratorConfig(classname=None, slice_def=()) batch_size=10 preferred_backend='threads' tile_shape=None output_type='dataframe' output_shape=None output_axes=None recompute_scale=False squeeze=True split_axis=None split_channels=False rename_channel=None index_on='object_id' properties=['aspect_ratio', 'stack_id', 'bbox', 'centroid', 'object_id', 'slice_id', 'area', 'label', 'cross_sectional_area', 'volume'] map_axes=True expand_coordinates=False
2026-07-06 15:58:04,814 - INFO - StackProcessor.run: received workers=-1 (type: <class 'int'>)
2026-07-06 15:58:04,824 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['Dpn']
2026-07-06 15:58:04,851 - INFO - RegionAnalyzer: Applying scale: (-0.9999284782608696, 0.3000933463796477, 0.3000933463796477), labels.shape=(93, 512, 512), channel_names=['EdU']
2026-07-06 15:58:05,394 - INFO - Identified 204 regions, return as dataframe
2026-07-06 15:58:05,397 - INFO - Finished in state Completed()
2026-07-06 15:58:05,412 - INFO - Finished in state Completed()
2026-07-06 15:58:05,515 - INFO - Identified 457 regions, return as dataframe
2026-07-06 15:58:05,517 - INFO - Finished in state Completed()
2026-07-06 15:58:05,521 - INFO - Finished in state Completed()
2026-07-06 15:58:05,738 - INFO - Identified 659 regions, return as dataframe
2026-07-06 15:58:05,740 - INFO - Finished in state Completed()
2026-07-06 15:58:05,743 - INFO - Finished in state Completed()
2026-07-06 15:58:05,821 - INFO - Identified 2 regions, return as dataframe
2026-07-06 15:58:05,823 - INFO - Finished in state Completed()
2026-07-06 15:58:05,825 - INFO - Finished in state Completed()
2026-07-06 15:58:06,106 - INFO - HTTP Request: POST https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/logs/ "HTTP/1.1 202 Accepted"
2026-07-06 15:58:06,126 - INFO - Identified 1 regions, return as dataframe
2026-07-06 15:58:06,127 - INFO - Finished in state Completed()
2026-07-06 15:58:06,130 - INFO - Finished in state Completed()
2026-07-06 15:58:06,159 - INFO - Setting up overlap calculator for pairs: [('Brain', 'Lobe'), ('Brain', 'Scrib'), ('Brain', 'EdU'), ('Brain', 'Dpn'), ('Lobe', 'Brain'), ('Lobe', 'Scrib'), ('Lobe', 'EdU'), ('Lobe', 'Dpn'), ('Scrib', 'Brain'), ('Scrib', 'Lobe'), ('Scrib', 'EdU'), ('Scrib', 'Dpn'), ('EdU', 'Brain'), ('EdU', 'Lobe'), ('EdU', 'Scrib'), ('EdU', 'Dpn'), ('Dpn', 'Brain'), ('Dpn', 'Lobe'), ('Dpn', 'Scrib'), ('Dpn', 'EdU')]
2026-07-06 15:58:06,611 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-07-06 15:58:06,645 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True
2026-07-06 15:58:06,723 - INFO - Running OverlapCalculator with config: classname='Configurable' package='vistiq.core' version=None command_group=None builder=LabelBuilderConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) area_calculator=LabelAreaCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None) intersection_calculator=LabelIntersectionCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, preferred_input_type='numpy', preferred_device=None, mode='auto', total_memory_limit=512, pair_memory_limit=512, dense_pair_fraction=0.3, max_bbox_volume_fraction=0.25) metrics_calculators=[IoSMetricsCalculatorConfig(classname='Configurable', package='vistiq.core', version=None, command_group=None, name='ios')] return_components=False triangle=7 output_type='dataframe' annotate=True

In [17]:
stackview.slice(np.concatenate(combined_labels, axis=-1))

HBox(children=(VBox(children=(VBox(children=(HBox(children=(VBox(children=(ImageWidget(height=512, width=2560)…

In [34]:
#for k,v in measurements.items():
#    print (k, type(v))

# Query graph for object ancestor lineage

1. Subcellular cellular Dpn -> tissue lobe -> organ brain
2. Count descendants in each channel

In [36]:
dag = measurements["containment_graph"]

gqcfg = GraphQueryConfig(
    attributes=["descendant_counts", "ancestor_lineage"],
    filter_attribute="channel",
    filter_value="Lobe",
    include_attributes=["object_name", "label", "channel", "volume"],
    lineage_value_attribute="label",
)
gq = GraphQuery(gqcfg)
gqfmt = GraphQueryFormatter(GraphQueryFormatterConfig())
result = gq.run(dag, node=None)
df_counts = gqfmt.run(result, attribute="descendant_counts")
df_lineage = gqfmt.run(result, attribute="ancestor_lineage")
df = pd.concat([df_counts, df_lineage], axis=1)
df = df.loc[:, ~df.columns.duplicated()].sort_values(["label"])
df

2026-07-06 16:13:07,784 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:07,827 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:07,835 - INFO - Summarizing graph with config: classname='Configurable' package='vistiq.core' version=None command_group=None label_attribute='object_name' group_attribute='channel' filter_attribute='channel' filter_value='Lobe' include_attributes=['object_name', 'label', 'channel', 'volume'] lineage_value_attribute='label' weight_attribute='ios' neighbor_analysis=None neighbor_k=None neighbor_radius=None source_filter=None target_filter=None source_nodes=None predecessor_match=None seed_nodes=None attributes=['descendant_counts', 'ancestor_lineage'] output_type='dataframe' output_index='object_id'
2026-07-06 16:13:07,837 - INFO - Node: None
2026-07-06 16:13:07,840 - INFO - Finished in state Completed()
2026-07-06 16:13:07,907 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:07,948 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:07,957 - INFO - Finished in state Completed()
2026-07-06 16:13:08,033 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:08,079 - INFO - HTTP Request: GET https://api.prefect.cloud/api/accounts/fe04c388-039f-4a9a-8a38-6ddd01791c77/workspaces/0aefefee-2869-4637-89ac-c510d86c639e/admin/storage "HTTP/1.1 404 Not Found"
2026-07-06 16:13:08,088 - INFO - Finished in state Completed()

,object_name,channel,label,volume,count Scrib,count Dpn,count EdU,lineage Brain
object_id,,,,,,,,
1d6dcdda74614b24ac6fa57eb4321a3e,Lobe 1,Lobe,1,296992.595265,151,93,173,1
7a045e0e38db467a84e1b40bfe82f787,Lobe 2,Lobe,2,286420.504943,138,92,187,1

In [22]:
from pyvis.network import Network

net = Network(notebook=True, cdn_resources='in_line', bgcolor="#222222", font_color="white", select_menu=True)
net.barnes_hut()

# Convert the networkx object
net.from_nx(dag.raw)
neighbor_map = net.get_adj_list()

# add neighbor data to node hover data
for node in net.nodes:
    node["title"] = node["object_name"] #+ "\n" +"  Neighbors:\n" + "\n".join(neighbor_map[node["id"]])
    #node["value"] = len(neighbor_map[node["object_name"]])

# Render
net.show("nx_graph.html")

nx_graph.html

In [23]:
net.show_buttons(filter_=['physics'])

# Summary

In [32]:
# add binary +/- categorization for channel overlap (based on channel overlap count) 
features=measurements["region_analyzer_all"].sort_values(["channel","label"])
for ch in np.unique(features["channel"]):
    count_col = f"count {ch}"
    if count_col in features.columns.values:
        features[f"{ch} +"] = features[count_col]>0
features.columns.values

array(['bbox-start-z', 'bbox-start-y', 'bbox-start-x', 'bbox-end-z',
       'bbox-end-y', 'bbox-end-x', 'centroid-z', 'centroid-y',
       'centroid-x', 'label', 'aspect_ratio-yz', 'aspect_ratio-xz',
       'aspect_ratio-xy', 'aspect_ratio', 'cross_sectional_area-yz',
       'cross_sectional_area-xz', 'cross_sectional_area-xy', 'volume',
       'channel', 'stack_id', 'slice_id', 'object_name', 'count Dpn',
       'count EdU', 'count Lobe', 'count Scrib', 'lineage Brain',
       'lineage Dpn', 'lineage EdU', 'lineage Lobe', 'lineage Scrib',
       'knn_count_Dpn_(k=5)', 'knn_count_EdU_(k=5)',
       'knn_count_Lobe_(k=5)', 'knn_count_Scrib_(k=5)',
       'knn_mean_distance_Dpn_(k=5)', 'knn_mean_distance_EdU_(k=5)',
       'knn_mean_distance_Lobe_(k=5)', 'knn_mean_distance_Scrib_(k=5)',
       'knn_nearest_neighbor_distance_Dpn_(k=5)',
       'knn_nearest_neighbor_distance_EdU_(k=5)',
       'knn_nearest_neighbor_distance_Lobe_(k=5)',
       'knn_nearest_neighbor_distance_Scrib_(k=5)',
       'knn_nearest_neighbor_id_Dpn_(k=5)',
       'knn_nearest_neighbor_id_EdU_(k=5)',
       'knn_nearest_neighbor_id_Lobe_(k=5)',
       'knn_nearest_neighbor_id_Scrib_(k=5)', 'rnn_count_Dpn_(radius=25)',
       'rnn_count_EdU_(radius=25)', 'rnn_count_Scrib_(radius=25)',
       'rnn_mean_distance_Dpn_(radius=25)',
       'rnn_mean_distance_EdU_(radius=25)',
       'rnn_mean_distance_Scrib_(radius=25)',
       'rnn_nearest_neighbor_distance_Dpn_(radius=25)',
       'rnn_nearest_neighbor_distance_EdU_(radius=25)',
       'rnn_nearest_neighbor_distance_Scrib_(radius=25)',
       'rnn_nearest_neighbor_id_Dpn_(radius=25)',
       'rnn_nearest_neighbor_id_EdU_(radius=25)',
       'rnn_nearest_neighbor_id_Scrib_(radius=25)', 'Dpn +', 'EdU +',
       'Lobe +', 'Scrib +'], dtype=object)

In [33]:
# reorder columns
cols = list(features.columns.values)
print (cols)
basics = ["label", "object_name", "channel","lineage Lobe"] 
positives = [c for c in cols if "+" in c] 
counts = [c for c in cols if "count" in c]
lineage = []#[c for c in cols if "lineage" in c]
rest = [c for c in cols if c not in (basics+positives+counts+lineage)]
reordered_cols = basics + counts + positives + lineage + rest
features = features[reordered_cols]
features[basics+positives].groupby(["lineage Lobe", "channel","EdU +"]).count()

#features[["channel", "object_name", "lineage Lobe"]].groupby(["lineage Lobe", "channel"]).count()
#features[(features["channel"]=="Dpn") & (~features["count EdU"].isna())]["count EdU"]

['bbox-start-z', 'bbox-start-y', 'bbox-start-x', 'bbox-end-z', 'bbox-end-y', 'bbox-end-x', 'centroid-z', 'centroid-y', 'centroid-x', 'label', 'aspect_ratio-yz', 'aspect_ratio-xz', 'aspect_ratio-xy', 'aspect_ratio', 'cross_sectional_area-yz', 'cross_sectional_area-xz', 'cross_sectional_area-xy', 'volume', 'channel', 'stack_id', 'slice_id', 'object_name', 'count Dpn', 'count EdU', 'count Lobe', 'count Scrib', 'lineage Brain', 'lineage Dpn', 'lineage EdU', 'lineage Lobe', 'lineage Scrib', 'knn_count_Dpn_(k=5)', 'knn_count_EdU_(k=5)', 'knn_count_Lobe_(k=5)', 'knn_count_Scrib_(k=5)', 'knn_mean_distance_Dpn_(k=5)', 'knn_mean_distance_EdU_(k=5)', 'knn_mean_distance_Lobe_(k=5)', 'knn_mean_distance_Scrib_(k=5)', 'knn_nearest_neighbor_distance_Dpn_(k=5)', 'knn_nearest_neighbor_distance_EdU_(k=5)', 'knn_nearest_neighbor_distance_Lobe_(k=5)', 'knn_nearest_neighbor_distance_Scrib_(k=5)', 'knn_nearest_neighbor_id_Dpn_(k=5)', 'knn_nearest_neighbor_id_EdU_(k=5)', 'knn_nearest_neighbor_id_Lobe_(k=5)', 'knn_nearest_neighbor_id_Scrib_(k=5)', 'rnn_count_Dpn_(radius=25)', 'rnn_count_EdU_(radius=25)', 'rnn_count_Scrib_(radius=25)', 'rnn_mean_distance_Dpn_(radius=25)', 'rnn_mean_distance_EdU_(radius=25)', 'rnn_mean_distance_Scrib_(radius=25)', 'rnn_nearest_neighbor_distance_Dpn_(radius=25)', 'rnn_nearest_neighbor_distance_EdU_(radius=25)', 'rnn_nearest_neighbor_distance_Scrib_(radius=25)', 'rnn_nearest_neighbor_id_Dpn_(radius=25)', 'rnn_nearest_neighbor_id_EdU_(radius=25)', 'rnn_nearest_neighbor_id_Scrib_(radius=25)', 'Dpn +', 'EdU +', 'Lobe +', 'Scrib +']

                            label  object_name  Dpn +  Lobe +  Scrib +
lineage Lobe channel EdU +
1.0          Dpn     False     65           65     65      65       65
                     True      28           28     28      28       28
             EdU     False    173          173    173     173      173
             Scrib   False    139          139    139     139      139
                     True      12           12     12      12       12
2.0          Dpn     False     69           69     69      69       69
                     True      23           23     23      23       23
             EdU     False    187          187    187     187      187
             Scrib   False    126          126    126     126      126
                     True      12           12     12      12       12

# Hierarchical label decomposition

# View in Napari

In [24]:
import napari
viewer = napari.Viewer()

In [27]:
scale = metadata["physical_pixel_sizes"]
channel_colors = ("green", "blue", "red")
nimg = img#np.expand_dims(img, axis=0)

# add labels, colormap={1: 'yellow', 2: 'cyan'},
for meta, l in zip(combined_metadata,combined_labels):#, combined_measurements):
    ch = "".join(meta.get("channel_names"))
    ch_features = features.loc[features["channel"]==ch]
    new_m = ch_features.copy().reset_index() #m.copy().reset_index()
    background = pd.DataFrame({c: [0] if c=="label" else [np.nan] for c in new_m.columns.to_list()})
    new_m = pd.concat([background, new_m], ignore_index=True)
    viewer.add_labels(l, name=f"{ch}-Labels", features=new_m, scale=scale, blending="translucent_no_depth", opacity=0.3, rendering="translucent")

# add cell labels for each channel
ch_images, ch_metadata = unstack_image(img, metadata=metadata, axis="C", strict=False)
for name, c_img, color in zip(metadata["channel_names"], ch_images, channel_colors):
    viewer.add_image(c_img, name=f"{name}", scale=scale, colormap=color, blending="additive", visible=False)

2026-07-06 16:00:03,040 - INFO - Unstacked image data along C axis with index 0. Data shapes: [(93, 512, 512), (93, 512, 512), (93, 512, 512)]

In [28]:
for ch in np.unique(features["channel"]):
    ch_features = features.loc[features["channel"]==ch]["label"]
    ch_viewer = np.unique(viewer.layers[f"{ch}-Labels"].data)
    print (f"{ch}, Features: {len(np.unique(ch_features))}, {len(ch_features)}, Viewer: {len(ch_viewer)}, {np.max(ch_viewer)+1}")

Brain, Features: 1, 1, Viewer: 2, 2
Dpn, Features: 185, 185, Viewer: 205, 205
EdU, Features: 360, 360, Viewer: 660, 660
Lobe, Features: 2, 2, Viewer: 3, 3
Scrib, Features: 289, 289, Viewer: 458, 458

# Visualize graph

In [29]:
def remove_edu(node):
    print (type(node))
    return True #dag.nodes[node].channel!="EdU"

In [30]:
import networkx as nx
dag = measurements["containment_graph"]

non_edu_nodes = [node for node, attr in dag.nodes(data=True) if attr.get("channel") not in ["EdU", "Scrib"]]


ndag = dag.subgraph(non_edu_nodes)

In [31]:
from vistiq.graph import nodes_to_layer, edges_to_layer

points = nodes_to_layer(
    ndag,
    "hierarchy nodes",
    node_face_color="EdU +",
    node_face_colormap=["magenta", "green", "red", "blue", "yellow"],
    #node_border_width=3,
    node_border_color="white",
    node_symbol="lineage Lobe",
    node_opacity=0.9,
    node_size=12,
    node_properties=features,
    editable=False,
)
vectors = edges_to_layer(
    ndag,
    "hierarchy edges",
    edge_color="lineage Lobe",
    edge_colormap="magma",
    edge_thickness=1.5,
    edge_opacity=0.35,
    editable=False,
)
viewer.add_layer(points)
viewer.add_layer(vectors)

UserWarning: The provided colors parameter contained illegal values, resetting all colors values to white.